pmodels/argobots

src/pool/fifo.c

Fix a bug and warnings which have been introduced in #57.

FIFO: Fix a bug and warnings.

---

src/include/abt.h.in
src/include/abti.h
src/info.c
src/stream.c
test/.gitignore
test/basic/Makefile.am
test/basic/info_stackdump.c
test/basic/info_stackdump2.c

This PR is a prototype to address #12.

Add a stack dump feature.

---

src/stream.c
src/thread.c

Fixes bugs introduced by #124.

local: fix improper TLS handling

---

configure.ac
src/global.c
src/include/abtd_thread.h
src/include/abtd_ucontext.h
src/include/abti.h
src/sched/sched.c
src/thread.c
test/basic/self_type.c
test/util/abttest.h

This PR fixes warnings to pass all the tests in https://jenkins-pmrs.cels.anl.gov/view/bolt/job/argobots-review-centos-all.

Fix miscellaneous warnings

---

src/info.c

`ABTI_info_check_print_all_thread_stacks()` refers to `gp_ABTI_global->num_xstreams` and accesses execution streams based on this value without taking `gp_ABTI_global->xstreams_lock`. This behavior potentially causes an error if execution streams are dynamically created/removed while traversing and printing elements in a pool.
This patch adds a lock (`gp_ABTI_global->xstreams_lock`) to avoid this situation. In addition, introducing a critical section can remove meaningless atomic load of `gp_ABTI_global->num_xstreams` (`ABTD_atomic_load_int32(&gp_ABTI_global->num_xstreams)`).

info: make a stack print function more robust

---

examples/stencil/stencil_helper.h

This PR fixes a bug in examples/stencil code.

examples/stencil: fix validation code

---

examples/stencil/stencil_barrier.c
examples/stencil/stencil_depend_future.c
examples/stencil/stencil_depend_mutex_cond.c
examples/stencil/stencil_depend_yield.c
examples/stencil/stencil_forkjoin.c
examples/stencil/stencil_forkjoin_divconq.c
examples/stencil/stencil_forkjoin_divconq_hrws.c
examples/stencil/stencil_forkjoin_divconq_rws.c
examples/stencil/stencil_forkjoin_revive.c
examples/stencil/stencil_forkjoin_task.c
examples/stencil/stencil_forkjoin_task_revive.c
examples/stencil/stencil_forkjoin_ws.c
examples/stencil/stencil_helper.h
examples/stencil/stencil_naive.c
examples/stencil/stencil_seq.c
src/stream.c

This PR fixes several issues found in testing other PRs on other machines. They are small bug fixes and do not affect the performance.

fix miscellaneous issues

---

src/include/abti_mem.h

This PR fixes the Valgrind registration code which was broken by #183.  To avoid such a bug in the future, the normal Jenkins test will check `--enable-valgrind` as one of the random options.

mem: fix Valgrind code

---

src/key.c

This fixes a bug in `ABTI_ktable_alloc_elem()`.

key: fix a bug

---

test/util/abttest.c

pthread_spinlock is not supported on some UNIX machines (e.g., OSX). This PR replaces `pthread_spinlock` with `pthread_mutex` in the test code (for the tool interface).
This is is used in testing, so the performance is not important.

test: replace pthread_spinlock with pthread_mutex

---

examples/profiling/abtx_prof.h
examples/profiling/daxpy.c

This PR fixes miscellaneous bugs in `ABTX_prof`.

examples/profiling: fix ABTX_prof

---

configure.ac
src/log.c
src/thread.c
test/basic/xstream_barrier.c

This PR fixes a few issues found while I was testing Argobots.

Miscellaneous fixes

---

examples/profiling/async_engine.c
examples/scheduling/sched_and_pool_user.c
examples/stencil/stencil_forkjoin_divconq_hrws.c
src/global.c
src/include/abti.h
src/include/abti_sched.h
src/include/abti_stream.h
src/include/abtu.h
src/sched/sched.c
src/stream.c
src/thread.c
test/basic/sched_prio.c

This PR fixes memory issues Clang and GCC address sanitizers found.

Fix memory errors found by address sanitizers

---

.github/workflows/CI.yml

The previous script does not work well if a script is triggered by merging a PR. This PR fixes it.

ci: fix the GitHub workflow CI.

---

configure.ac
src/include/abtd_context.h
src/include/abtd_ythread.h
src/info.c
src/log.c
src/pool/pool.c
src/sched/sched.c
src/stream.c
src/thread.c
src/thread_attr.c

This PR factors miscellaneous issues to be friendly with various non-mainstream compilers (e.g., PGI).
Note that insights of these changes came from C++; all the issues fixed by this PR are complained by C++ compilers.

minor code refactoring

---

src/cond.c

Internal static functions should be declared after public `ABT_` functions.  This PR fixes it.
This fix is minor; it won't affect the performance of Argobots.

cond: declare static functions at the bottom of the code file

---

src/error.c
src/include/abt.h.in
test/.gitignore
test/basic/Makefile.am
test/basic/error.c

This PR fixes `ABT_error_get_str()` and adds a test to check this functionality.

Fix error string

---

src/futures.c

```c
void thread1(void *) {
while (1) {
ABT_bool flag;
ABT_future_test(future, &flag);
if (flag == ABT_TRUE)
printf("future is ready!\n");
}
}
void thread2(void *) {
ABT_future_set(future, NULL);
}
```
`ABT_future_test()` could return `ABT_TRUE` before `ABT_future_set()` calls a callback function. Though this behavior is not mentioned in the Argobots' document, the callback function should be called before the future becomes ready so that waiters can depend on execution done by the callback function.
This patch guarantees that a callback function is called before a future gets ready.
No performance impact is expected. This change should not affect the behavior of existing applications.

future: call a callback function before making a future ready

---

Doxyfile.in
src/timer.c

This PR updates the specification of the current timer API for the upcoming Argobots 1.1.
This PR only clarifies the behavior of timer routines. There is no major change in terms of functionality.

timer: improve API

---

Doxyfile.in
src/key.c

This PR improves the API and its explanation of `ABT_key_xxx()` functions for the upcoming Argobots 1.1. This PR does not break the API of Argobots 1.0.

key: improve API

---

Doxyfile.in
src/include/abt.h.in
src/task.c
test/basic/self_type.c
test/basic/thread_task.c

This PR improves the API and its explanation of `ABT_task_xxx()` functions for the upcoming Argobots 1.1.
This PR does not change the API of Argobots 1.0.

task: improve API

---

Doxyfile.in
src/error.c
src/global.c
src/include/abt.h.in
src/unit.c
test/basic/error.c

This PR improves the API and its explanation of "the other functions, types, and constant values" (e.g., init/finalize, error, unit)  for the upcoming Argobots 1.1.
This PR does not break the API of Argobots 1.0.

misc: cleanup API

---

Doxyfile.in
src/cond.c
src/error.c
src/eventual.c
src/include/abt.h.in
src/pool/pool.c
src/sched/sched.c
src/stream.c
src/thread.c

This PR fixes comments to make the doxygen document better. This PR updates only comments so it does not change the behavior of Argobots.

doxygen: update comments

---

.github/pull_request_template.md
.github/workflows/CI.yml

This PR updates the GitHub support to ease the Argobots development especially for external developers. Specifically, this PR fixes the following items:
1. Check `c90` (actually `gnu90`) compilation support (#289)
2. Add a PR template to clarify the Argobots' development rule (#290)
This PR closes #292.

Update GitHub support

---

Doxyfile.in
README.md
maint/release.pl
src/eventual.c
src/futures.c
src/global.c
src/include/abt.h.in
src/info.c
src/key.c
src/mutex.c
src/mutex_attr.c
src/pool/pool.c
src/rwlock.c
src/sched/config.c
src/sched/sched.c
src/self.c
src/stream.c
src/stream_barrier.c
src/task.c
src/thread.c
src/thread_attr.c
src/timer.c
src/tool.c
src/unit.c

This PR cleans up Doxygen files and README.md for the upcoming 1.1b1 release.
This PR does not change the real code.

update doxygen comments and README.md for the upcoming release

---

CHANGES
maint/version.m4

This PR update the version information to release Argobots 1.1b1.

Argobots release 1.1b1

---

examples/hello_world/hello_world.c
examples/hello_world/hello_world_ws.c
examples/profiling/abtx_prof.h
examples/stencil/stencil_forkjoin_divconq.c
examples/stencil/stencil_forkjoin_divconq_hrws.c
examples/stencil/stencil_forkjoin_divconq_rws.c
examples/stencil/stencil_helper.h
src/arch/abtd_affinity_parser.c
src/arch/abtd_env.c
src/arch/abtd_stream.c
src/include/abti_mem_pool.h
src/sched/config.c
src/stream.c

This PR fixes bugs found by Coverity. This PR also suppresses warnings issued by Coverity to get better information.
After merging this PR, Argobots should be green for the following configurations (except for `test/`, which is currently excluded):
```sh
./configure
./configure --enable-perf-opt
./configure --enable-debug=yes --enable-stack-overflow-check=canary-16
./configure --disable-fcontext
./configure --enable-ver20-api
./configure --enable-feature=no
./configure --enable-fcontext --enable-dynamic-promotion --enable-affinity \
--enable-wait-policy=active --enable-tool
```
We will set up a nightly Coverity to check those configurations.

fix bugs/warnings found by Coverity

---

m4/aclocal_runlog.m4
maint/Version.base.m4
maint/spellcheck.bash
src/arch/fcontext/jump_x86_64_sysv_elf_gas.S
src/arch/fcontext/make_i386_sysv_macho_gas.S
src/include/abti_mem.h
test/basic/thread_task.c
test/util/abttest.h

This PR applies codespell (https://github.com/codespell-project/codespell) and fixes typo.

add spellcheck 

---

src/pool/fifo.c
src/pool/fifo_wait.c

`pool_pop()` of the current builtin pool implementations takes a look and then checks the pool size, but this lock is unnecessary if the pool is empty.  This lock acquisition causes significant performance degradation when there are fewer producers than consumers; `pool_push()` operations are delayed by the `pool_pop()`'s lock although that `pool_pop()` will fail since the pool is empty.
This patch adds a quick size check before taking a lock so that `pool_pop()` can return without taking a lock if the pool is empty.
In the benchmark, only one execution stream creates 10000 ULTs.  All the execution streams access the same pool to execute the created empty ULTs.  The following result shows the relative execution time while the performance of the current main Argobots is 1 (so smaller is …

pool: check the pool's emptiness before taking a lock

---

CHANGES
maint/version.m4

This PR releases Argobots 1.1.

Argobots release 1.1

---

src/pool/pool.c

This PR fixes an issue found by Coverity: https://scan.coverity.com/projects/argobots

pool: remove an unnecessary pointer check
