pmodels/argobots

- src/thread.c
Fix inverted current thread != target thread check that was causing
warning message and yield_to() failure
> fix logic bug in yield_to()

- src/eventual.c
- src/include/abt.h.in
- test/basic/eventual_create.c
A thread might want to overlap waiting on an eventual with other activities. The
current eventual interface only allow a blocking wait operation. This patch
extends the eventual interface with a nonblocking routine; ABT_eventual_test.
> eventual: added a nonblocking test API

- configure.ac
- src/arch/abtd_env.c
- src/include/abti.h
- src/include/abti_mem.h
- src/info.c
- src/mem/malloc.c
Solve #19  It improves performance by embedding the constant.
Specifically, users can specify one of the following:
- auto: use the automatic cache line size detection. It uses 64 if all attempts fail.
- specific value (e.g., “64”): use that value.
- otherwise (default): use an environmental variable, or use 64 if it is not set.
Internally, the following command is used for Linux:
``cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size | grep -Po '^(\d+)$'``
I checked it on the following environments:
- Red Hat 7.4 + POWER8 ... OK
- Red Hat 7.4 + Intel Xeon ... OK
- Red Hat 7.4 + Intel Xeon Phi (KNL) ... OK
- Ubuntu 16.04 + Intel Xeon ... OK
- VMWare Ubuntu 16.04 + Intel Core i7 ... OK
- openSUSE 42.2 Arm64 (ARM Cortex 8) ... NG
Note I could not find any command working for …
> #19 Cache line size can be statically obtained on configuration.

- src/thread.c
This commit is to avoid the underestimation of the pool size on
joining, which affects the scheduling behavior.
Specifically, ABTI_sched_has_to_stop() returns TRUE (i.e., stops a
scheduler) when ABTI_sched_get_effective_size() is 0.
https://github.com/pmodels/argobots/blob/master/src/sched/sched.c#L460
Because ABTI_sched_get_effective_size() calculates the effective
size by adding blocked_num and the current pool size, blocked_num
must be increased "before" extracting a unit from a pool.
https://github.com/pmodels/argobots/blob/master/src/sched/sched.c#L659
Previously, this problem might cause the following case:
1. A pool is shared by multiple schedulers.
2. One scheduler picks up a thread in a pool on joining.
3. Though the true effective size of this pool is not zero, the
otherd think …
> Avoid underestimation of pool size

- src/cond.c
- src/include/abti_cond.h
- test/basic/cond_test.c
This PR fixes a bug of ``ABTI_cond_broadcast`` (no corresponding issue)
The previous ``ABT_cond_timedwait`` and ``ABTI_cond_wait`` try to obtain
``p_cond``'s mutex by spinlock, which causes a deadlock.  It often
happens when waiting threads are signaled simultaneously by
``ABT_cond_broadcast``, and a thread taking a lock yield to another
awaken threads.
By replacing spinlock with a normal mutex lock, another awaken
threads can again yield and the thread taking a lock can be resume.
This commit also changed a test to check this behavior.  The old
Argobots will freeze with ``cond_test``, while this commit passes that
test.
> Fix a bug of ABT_cond_broadcast.

- src/include/abti_mem.h
- src/include/abti_valgrind.h
- src/mem/Makefile.mk
- src/mem/valgrind.c
- src/thread.c
This problem has been mentioned in #10.
This PR is to support Valgrind.
When`` --enable-valgrind`` is given and compiled with debuging flags,
Argobots registers all stacks allocated from heaps to Valgrind so
that Valgrind can correctly handle stacks used by threads. It is
completely ignored and thus does not affect performance when
Valgrind is disabled (by default), or compiled with debugging flags.
> Valgrind Support

- src/error.c
Add missing error string for `ABT_ERR_INV_MUTEX_ATTR` to  the lookup
table for error strings.
This fixes a bug that lead to:
* segmentation fault when `ABT_error_str` is called with `err==ABT_ERR_FEATURE_NA`
* incorrect error strings for `err>ABT_ERR_INV_MUTEX`
> Add missing error string in ABT_error_get_str

- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_pool.h
- src/pool/Makefile.mk
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/Makefile.mk
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/sched/sched.c
- test/basic/Makefile.am
- test/basic/sched_basic_wait.c
This adds a new predefined scheduler type called ABT_SCHED_BASIC_WAIT that will block when idle if used in conjunction with ABT_POOL_FIFO_WAIT.
Includes test program and minor change to sched_create_basic() to make it use pool of type POOL_FIFO_WAIT by default with SCHED_BASIC_WAIT if the caller does not specify an explicit pool to use.
This is the revised version of PR #49. This PR includes generic improvements from PR #47 and PR #48 .
Corresponding branch of margo that uses this capability can be found at https://xgitlab.cels.anl.gov/sds/margo/tree/dev-fifo-wait
> implement ABT_SCHED_BASIC_WAIT (revised)

- src/arch/fcontext/jump_arm64_aapcs_elf_gas.S
- src/arch/fcontext/jump_arm64_aapcs_macho_gas.S
- src/arch/fcontext/jump_i386_sysv_elf_gas.S
- src/arch/fcontext/jump_i386_sysv_macho_gas.S
- src/arch/fcontext/jump_ppc32_sysv_elf_gas.S
- src/arch/fcontext/jump_ppc32_sysv_macho_gas.S
- src/arch/fcontext/jump_ppc64_sysv_elf_gas.S
- src/arch/fcontext/jump_ppc64_sysv_macho_gas.S
- src/arch/fcontext/jump_x86_64_sysv_elf_gas.S
- src/arch/fcontext/jump_x86_64_sysv_macho_gas.S
- src/arch/fcontext/take_arm64_aapcs_elf_gas.S
- src/arch/fcontext/take_arm64_aapcs_macho_gas.S
- src/arch/fcontext/take_i386_sysv_elf_gas.S
- src/arch/fcontext/take_i386_sysv_macho_gas.S
- src/arch/fcontext/take_ppc32_sysv_elf_gas.S
- src/arch/fcontext/take_ppc32_sysv_macho_gas.S
- src/arch/fcontext/take_ppc64_sysv_elf_gas.S
- src/arch/fcontext/take_ppc64_sysv_macho_gas.S
- src/arch/fcontext/take_x86_64_sysv_elf_gas.S
- src/arch/fcontext/take_x86_64_sysv_macho_gas.S
- src/include/abtd_thread.h
This PR improves performance.
Embed FPU preservation check into assembly code to reduce instructions.
Previously, `preserve_fpu` flag was passed to `jump_fcontext` and `take_fcontext` functions and checked in the assembly functions. `preserve_fpu` is compile-time constant, but `xxx_fcontext` functions cannot be inlined because they are written in assembly, which incurs a runtime overhead.
Now the macro (`#if ABTD_FCONTEXT_PRESERVE_FPU`) is embedded into the assembly code, so there is no runtime overhead. This optimization reduces at least 6 instructions (including 3 branches) per fork-join operation.
> Inline fpu check

- src/arch/abtd_thread.c
- src/include/abti.h
- src/thread.c
Remove restrictions of `ABT_thread_create_many`, `ABT_thread_join_many`, and `ABT_thread_free_many` by removing an experimental join_many feature.
These functions create, join and free many threads, but the current implementation only works under very limited circumstances. This was a note of `ABT_thread_join_many`.
```
NOTE: The current implementation is very experimental. It works only for the
case where all ULTs in thread_list are mapped to the same ES as that of the
caller. They do not need to be in the same pool, but pools associated with
target ULTs should be exclusively associated with the caller's ES.
```
They also have an interoperability issue; threads created by `ABT_thread_create` cannot be joined by `ABT_thread_join_many` and vice versa.
This commit still keeps the functions …
> Simplify ABT_thread_xxx_many functions.

- src/global.c
- src/include/abti.h
- src/info.c
- src/mem/malloc.c
- src/stream.c
Originally, `p_xstreams` and task pages (`p_mem_task`) are managed by the same lock (`ABTI_global->lock`), though there is no conflict between them. To address this issue, this PR
1. adds a new lock, `ABTI_global->mem_task_lock` for the task page management, and
2. renames `ABTI_global->lock` to `ABTI_global->xstreams_lock` to clarity what it protects.
> Separate ABTI_global->lock

- src/stream.c
This commit fix a bug in `ABTI_xstream_free`. Please refer to the comment for details.
Note that this PR does not directly depend on #69, but the idea of this PR is clearer if this PR is merged after #69.
> Fix ABTI_xstream_free()

- configure.ac
- src/include/abtu.h
This PR adds `ABTU_likely` and `ABTU_unlikely` functions, which give hints to the compiler with branch prediction information. Those features are currently not used. They will be added in future.
> Add likely and unlikely

- configure.ac
- src/arch/abtd_thread.c
- src/barrier.c
- src/cond.c
- src/event.c
- src/eventual.c
- src/futures.c
- src/include/abtd.h
- src/include/abtd_atomic.h
- src/include/abtd_thread.h
- src/include/abti_cond.h
- src/include/abti_mutex.h
- src/include/abti_spinlock.h
- src/include/abti_stream.h
- src/include/abti_thread_htable.h
- src/mem/malloc.c
- src/mem/valgrind.c
- src/mutex.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_htable.c
This commit fully supports GCC's `__atomic` builtins providing precise memory semantics.
This commit does not only fix incorrect spinlocks (#38, #42, #44), but also gives correct implementations
for synchronization of `state`, `request`, `ext_signal` and so on which are previously accessed by multiple threads without any synchronization.
See commit logs for details.
> Support __atomic builtins.

- src/global.c
- src/include/abti_mem.h
- src/stream.c
- src/thread.c
`ABT_thread_create`, `ABTI_thread_create_sched`, `ABTI_thread_create_main`, and `ABTI_thread_create_main_sched` share most part of implementations, but they are individually coded, which significantly degrades maintainability.
This PR creates a new internal function `ABTI_thread_create` and makes all the `ABT(I)_thread_create_xxx` functions call `ABTI_thread_create`.
This does not affect the performance of `ABT_thread_create` if `ABTI_thread_create` is properly unrolled.
This PR is a prerequisite for #72.
> Unify ABT(I)_thread_create_xxx

- src/arch/abtd_thread.c
- src/global.c
- src/include/abtd_thread.h
- src/include/abti_thread.h
- src/mutex.c
- src/sched/sched.c
- src/stream.c
- src/thread.c
- src/thread_htable.c
Argobots has many implicit rules before calling `ABT_thread_context_switch` and `ABT_thread_finish context`;  `ABTI_LOG_SET_SCHED`, `ABTI_local_set_thread` and `ABTI_local_set_task` must be called properly before these functions.
This behavior is difficult to follow and very error-prone. To address this issue, this PR hides them from most code by splitting context switching functions;
- `ABT_thread_[context_switch/finish_context]_thread_to_thread`
- `ABT_thread_[context_switch/finish_context]_thread_to_sched`
- `ABT_thread_[context_switch/finish_context]_sched_to_thread`
- `ABT_thread_[context_switch/finish_context]_sched_to_sched`
This PR requires #76 in advance.
> Improve maintainability by splitting context switching functions

- src/arch/abtd_thread.c
- src/thread.c
Thread code uses `is_sched`. However, this variable is only declared when the
stackable scheduler is enabled. When this feature is disabled, compile-time
errors occur.
This PR fixes this issue by adding `#ifdef` macros.
> Fix compilation error when stackable scheduler is disabled.

- src/global.c
`ABT_init`, `ABT_finalize`, and `ABT_initialized` do not work well if multiple thread instance tries to call these functions. This situation often happens when multiple Argobots-based systems are employed.
This PR makes them thread safer.
> Thread safer  ABT_init/finalize/initialized

- src/include/abtd_atomic.h
Non x86-64 machines fail to compile Argobots, because `ABTD_atomic_pause()` uses an x86/64 specific instruction, `pause`.
This commit removes it when non x86-64 machines are used.
This change passes a quick test on an ARM 64 machine.
> Fix ABTD_atomic_pause.

- src/arch/abtd_thread.c
- src/include/abti_thread.h
Similar to #79, but it only happens with `--enable-debug=yes`; when the stackable scheduler feature is disabled, compilation error happens (`is_sched` is undefined). This PR fixes this issue by adding `#ifdef`.
> Fix the undefined is_sched error

- src/arch/abtd_thread.c
- src/include/abt.h.in
- src/include/abtd_ucontext.h
- src/include/abti.h
- src/info.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/thread.c
This PR adds a basic stack dump functionality.
- `ABT_info_print_thread_stack` prints a stack of a given thread.
- `ABT_info_print_thread_stack_in_pool` prints stack information of threads in a given pool.
This commit is a prerequisite for #68.
> Implement the basic stack dump functionality

- configure.ac
- src/include/abti_error.h
This PR adds an option to `--enable-debug`, `err`, which indicates whether failing function calls should print a message on standard error. By default this will now not be the case.
> made possible to remove error messages from std output

- src/include/abti_valgrind.h
- src/mem/valgrind.c
This enables users of argobots to keep one build that
supports valgrind without losing significant performance.
test:jenkins
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>
> Disable expensive valgrind specific tracking if valgrind isn't running

- configure.ac
Currently, Argobots uses an advanced mutex implementation using a hand-off mechanism by default.  However, this mutex algorithm has algorithmic issues.
1. it potentially causes SEGV (#14, #41)
2. it forces users to set the maximum number of execution streams before initialization (#34)
A quick hack does not work for these issues. We need to completely improve the current mutex implementation. It is the right way to fix these issues, but it requires longer time than I expect.
For stability, this PR disables the current experimental mutex implementation and uses the stable simple mutex algorithm, which does not have any reported issues.
Note that this change might negatively affect the mutex performance; one can enable the previous mutex by setting `--disable-simple-mutex`.
> configure: enable simple mutex by default

- src/global.c
- src/include/abti_error.h
This is an interim solution mentioned by @carns in #34.
This patch is simple; Argobots prints warning (only once) if # of ESs > `ABT_MAX_NUM_XSTREAMS` so that users can set a larger number to `ABT_MAX_NUM_XSTREAMS` (i.e., `ABT_MAX_NUM_XSTREAMS=XXX ./a.out`, or to do it in a program, see #35).
This is a real pain in the neck; currently the priority-/locality-aware mutex implementation (specifically `ABTI_thread_htable` uses a preallocated array whose size is `ABT_MAX_NUM_XSTREAMS` (by default, the number of cores), so any `ABT_mutex` created before creating all the execution streams can cause SEGV if the total number of executions streams happen to be larger than the number of cores). Many users complained about this annoying behavior.
Note that another possible option is returning an …
> Print warning when ABT_MAX_NUM_XSTREAMS is too small

- test/basic/info_stackdump2.c
This patch fixes the loop range in `test/basic/info_stackdump2.c` which sometimes causes an illegal memory free error.
The bug is as follows: `args[i][j].stack` is only initialized with `i != 1` (see line 143)
```c
/* Create ULTs. */
/* i starts from 1 because one execution stream must be busy-scheduling. */
for (i = 1; i < num_xstreams; i++) {
for (j = 0; j < num_threads; j++) {
[...]
args[i][j].stack = NULL;
```
while previously it iterates over all `args[i][j].stack`, some of which are uninitialized (see line 212).
```c
for (i = 0; i < num_xstreams; i++) { // this "0" is the problem
for (j = 0; j < num_threads; j++) {
if (args[i][j].stack)
free(args[i][j].stack);
}
[...]
```
> Fix test/basic/info_stackdump2.c

- src/arch/fcontext/jump_i386_sysv_elf_gas.S
- src/arch/fcontext/jump_i386_sysv_macho_gas.S
- src/arch/fcontext/take_i386_sysv_elf_gas.S
- src/arch/fcontext/take_i386_sysv_macho_gas.S
- src/include/abti_thread_htable.h
- src/log.c
This PR fixes the implementation of fcontext for i386 so that Argobots can be compiled on x86/32 systems.
On an x86/64 system, 32-bit Argobots can be built as follows (multilib support is necessary):
```sh
./configure --host=i686-pc-linux-gnu CFLAGS=-m32 CCASFLAGS=-m32
make
```
The mutex patch should address the issue #104, which was originally reported by @mdorier. Thanks, @mdorier!
> Support i386 (aka, 32-bit Intel architecture)

- src/cond.c
- src/event.c
- src/global.c
- src/include/abti.h
- src/include/abti_mutex.h
- src/include/abti_pool.h
- src/include/abti_self.h
- src/include/abti_stream.h
- src/include/abti_timer.h
- src/info.c
- src/log.c
- src/mutex.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
- src/timer.c
- src/unit.c
This commit removes all the internal use of public `ABT_` functions in Argobots and have the Argobots functions use private/internal `ABTI_` functions instead. This PR itself directly addresses #52 by making all the internal functions inlinable in theory (e.g., link-time optimization).
In addition, this PR is necessary for the following:
- Better error handling (e.g., #116): all errors must be handled in `ABT_` functions, not in `ABTI_`. To force so, `ABT_` functions should not call `ABT_` functions recursively.
- Fixing the TLS issue (#55, #111): one possible solution for this is passing a TLS variable across `ABTI_` functions. Doing so requires this PR.
An exception of this rule is `ABT_timer_get_overhead()`; it needs to get an overhead including the function call overhead, so …
> remove internal use of public ABT_ functions

- configure.ac
- src/arch/abtd_thread.c
- src/cond.c
- src/eventual.c
- src/futures.c
- src/global.c
- src/include/abti.h
- src/include/abti_cond.h
- src/include/abti_error.h
- src/info.c
- src/mem/malloc.c
- src/mutex_attr.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_attr.c
- src/thread_htable.c
- test/basic/sched_prio.c
This PR solves most warnings with `-Wall`, `-Wextra` to make Argobots warning free. Compiler warnings are useful to detect potential bugs. In the future the Jenkins will check warnings, making the review process easier.
The exceptions are `-Wunused-parameter` and `-Wsign-compare`. It is hard to justify a big code change just to fix them, so they are suppressed by `-Wno-unused-parameter` and `-Wno-sign-compare`.
EDIT: add `-Wno-maybe-uninitialized` since GCC 8.3's false positive warning regarding `memcpy` is annoying (it warns `memcpy` of automatically padded struct that has an uninitialized memory region: see http://www.open-std.org/jtc1/sc22/wg14/www/docs/dr_451.htm).
> Solve Most Warnings for CI

- src/include/abt.h.in
- src/info.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream_barrier.c
- src/task.c
- src/thread.c
- test/basic/task_data.c
This PR makes opaque types unique, and fixes several problems revealed by this.
The definition is changed as follows:
```
// Previous
typedef void *ABT_thread;
// New
struct ABT_thread_opaque;
typedef struct ABT_thread_opaque *ABT_thread;
```
This technique is very common. See https://en.wikipedia.org/wiki/Opaque_pointer for details.
This improvement revealed several problems (see the second commit).
For users, this change is beneficial in the following situation:
```
// ABT_thread_join(ABT_thread thread);
// ABT_thread_free(ABT_thread *thread);
ABT_thread thread = [...];
ABT_thread_join(&thread); // ERROR, but no warning previously
ABT_thread_free(&thread); // OK
```
It is because any pointer type (i.e., `&thread` = `void **`) can be converted to  `void *`.
After the improvement,  the …
> Introduce opaque pointers.

- src/thread.c
Unlike ABT_thread_free, ABT_thread_free_many did not join threads before freeing
threads.  This patch fixes this wrong behavior.
> thread: fix a bug in ABT_thread_free_many

- src/arch/abtd_thread.c
- src/include/Makefile.mk
- src/include/abtd.h
- src/include/abtd_context.h
- src/include/abtd_fcontext.h
- src/include/abtd_thread.h
- src/include/abtd_ucontext.h
- src/include/abti_thread.h
This PR provides (or revives) `ucontext` support, which is a fallback method when `fcontext` is unavailable.  The previous `ucontext` support was incomplete: compilation fails by `#error`. Though `fcontext` supports many platforms, this PR can widen the support architectures.
The first two commits remove the current incomplete and dirty `ucontext` implementation, and the third commit creates thin wrappers for `fcontext`, and the fourth commit implements their `ucontext` version. The last commit is clean-up.
This PR is related to #11, #18, and #81, all of which as a result encountered the unsupported `ucontext` error.
> Support ucontext

- src/arch/abtd_env.c
This is a workaround for #93.
When hugepage is used, `mmap()` needs a correct size of hugepage; otherwise, error happens on `munmap()`.  However, the default size is for typical x86/64 machines, not for other architectures, so the error happens when the hugepage size is different.  To run Argobots with default settings on these architectures, we disable hugepage allocation by default on non-x86/64 architectures; on such a machine, hugepage settings should be explicitly enabled via an environmental variable.
In the future, this issue should be fixed by using a correct hugepage size.
> Disable hugepage allocation by default on non-x86/64.

- src/include/abti.h
- src/include/abti_thread.h
- src/thread.c
This PR removes unused variables when `ABT_CONFIG_DISABLE_MIGRATION` is enabled, which removes a few initialization operations in `ABT_thread_create` and its friends.
PR  #65 is prerequisite.
> Remove unused thread variables

- src/sched/basic.c
This change to the basic scheduler algorithm checks for events after X ULTs rather than X passes
through all the pools. The core idea is that pop_count is a better metric to check for an event periodically compared with previous work_count (pop_count * num_pools) since this metric does not depend on the number of pools. Also, this change removed run_cnt variable and used unit variable as input for SCHED_SLEEP, which makes the code a bit cleaner since another variable is not required.
> sched: clean up the algorithm of the basic scheduler

- src/stream.c
Fixed the change in 99796faf60610f510ee5719e0dd82ea8c65a0e73.
ABT_xstream_create_basic() should start the created ES immediately as
well as ABT_xstream_create().
Fixes #133.
> xstream: start ESes in ABT_xstream_create_basic()

- src/futures.c
- src/include/abti_error.h
- src/stream_barrier.c
- src/task.c
This PR cleans up `ABTI_error.h`.
Previously, two implementations of `ABTI_CHECK_` and `HANDLE_xxx` macros exist based on `ABT_CONFIG_DISABLE_ERROR_CHECK` and `ABT_CONFIG_PRINT_ABT_ERRNO`. This PR creates constant values associated with `ABT_CONFIG_DISABLE_ERROR_CHECK` and `ABT_CONFIG_PRINT_ABT_ERRNO` and add a branch in the macros (without creating a macro).
Briefly speaking,
```c
#ifndef ABT_CONFIG_DISABLE_ERROR_CHECK
#define ABTI_CHECK_TRUE_RET(cond,val) \
do {                              \
if (!(cond)) {                \
return (val);             \
}                             \
} while(0)
#else
#define ABTI_CHECK_TRUE_RET(cond,val)
#endif
```
becomes the following.
```c
// ABT_CONFIG_IS_ERROR_CHECK_ENABLED is defined in another place.
#define ABTI_CHECK_TRUE_RET(cond,val) …
```
> Clean up ABTI_error.h

- src/event.c
- src/global.c
- src/include/abti_mem.h
- src/include/abti_stream.h
- src/include/abtu.h
- src/info.c
- src/sched/config.c
- src/thread_htable.c
Currently, some Argobots codes use `malloc`, `calloc` and `realloc` via `ABTU_malloc` etc in order to allocate data. Since these functions are not aware of cache line alignment. this allocation sometimes causes cache line conflict.
For example,
```
void case1() { // Conflict between Argobots objects
ABT_mutex mutex1, mutex2;
ABT_mutex_create(&mutex1); // It internally calls ABTU_calloc, which is mapped to calloc
ABT_mutex_create(&mutex2); // It internally calls ABTU_calloc, which is mapped to calloc
// mutex1 and mutex2 can share the same cache lines.
}
void case2() { // Conflict between an Argobot object and user data
ABT_mutex mutex;
ABT_mutex_create(&mutex); // It internally calls ABTU_calloc, which is mapped to calloc
int *user_data = (int *)malloc(sizeof(int) * 16);
// mutex and …
```
> abtu: always use aligned malloc.

- src/include/abt.h.in
- src/sched/config.c
- src/sched/sched.c
Add `ABT_sched_config_automatic` that did not exist though it was mentioned in the comment.
```
*     - ABT_sched_config_automatic: to automatically free the scheduler when
*     unused (ABT_TRUE by default)
```
Now users can overwrite `automatic` of `ABT_sched` by passing `ABT_sched_config`.
This PR addresses #59.
> sched: support ABT_sched_config_automatic.

- src/cond.c
- src/include/abti_cond.h
When the given mutex is invalid (i.e., when `ABTI_mutex_equal` returns false) `ABTI_cond_wait` and `ABT_cond_timedwait` go to `fn_fail` without freeing memory allocated in these functions.  This PR fixes this issue.
This is related to #96.
> cond: fix memory leak

- src/arch/abtd_affinity.c
- src/global.c
- src/include/abtd.h
The `cpuset` (affinity) of the main pthread is changed if `ABT_ENV_SET_AFFINITY` is on, but it is not restored at finialization, which limits the number of cores in the following execution.
For example,
```c
/* 1st exec */
ABT_init(0, NULL);
...
ABT_finalize();
/* 2nd exec */
ABT_init(0, NULL);
...
ABT_finalize();
```
the above second execution only uses one core even if multiple ESes are created, since the `cpuset` of the main pthread is set to `core 0` at `ABT_init()`.
Save `cpuset` at `ABT_init()`, and restore it at `ABT_finalize()`.
> global: restore cpuset (affinity) at ABT_finalize()

- src/mutex_attr.c
`ABT_mutex_attr_set_recursive()` uses atomic operations to update a recursive flag, but racy flag change should be forbidden (e.g., two threads try to change a recursive mode of the same `ABT_mutex_attr` simultaneously). This commit removes these unnecessary atomic operations.
> mutex_attr: remove unnecessary atomic operations

- configure.ac
Using an assignment statement (i.e., `weak = 0`) as a function argument incurs a compilation error with `-Werror`, preventing detection of `__atomic` builtins in configure.
Specifically, the error comes from the following:
```c
// GCC-9.2.0
int new = 0, old = 0, val = 0, weak;
val = __atomic_compare_exchange(&val, &old, &new, weak = 0,
__ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE);
```
causes the following warning, which becomes an error with `-Werror`.
```
warning: suggest parentheses around assignment used as truth value [-Wparentheses]
```
This patch fixes it by not using `(weak = 0)`; there's little sense to label the argument anyway.
> configure.ac: fix __atomic detection code

- src/barrier.c
- src/eventual.c
- src/futures.c
- src/global.c
- src/include/abti_cond.h
- src/include/abti_spinlock.h
- src/mem/malloc.c
- src/mem/valgrind.c
- src/pool/fifo.c
- src/stream.c
- src/thread.c
- src/thread_htable.c
This PR cleans up the interface of `ABTI_spinlock`. Specifically, `ABTI_spinlock` can be initialize statically and do not require explicit finalization, but the previous interface requires users to create it dynamically and free it before a program finishes.
This PR changes the interface of `ABTI_spinlock` as follows:
Added function and macro:
- `ABTI_spinlock_clear()`: a function that initializes lock. The term "clear" is established for this usage (for example, `std::atomic_flag::clear` and `__atomic_clear`).
- `ABTI_SPINLOCK_STATIC_INITIALIZER()`: a static initializer.
Removed functions:
- `ABTI_spinlock_create()`: it is renamed to `ABTI_spinlock_clear()` since there is no "release" operation for "clear".
- `ABTI_spinlock_free()`: it is removed since it does nothing.
This change can …
> Clean up the interface of ABTI_spinlock

- src/include/abti_error.h
- src/thread_htable.c
This PR adds a static assert macro, `ABTI_STATIC_ASSERT()`. Currently Argobots only supports `ABTI_ASSERT()`, which checks a given condition at execution time. However, some conditions are compile-time constant and thus should be checked at compile time. This macro uses a trick to implement a static assert macro similar to `BUILD_BUG_ON()` in the Linux kernel (http://lxr.linux.no/linux+v2.6.26.5/include/linux/kernel.h#L494).
> Add a static assert macro

- configure.ac
- m4/ax_gcc_func_attribute.m4
- src/include/abt.h.in
As discussed in #17, `ABT_thread_retain()`, `ABT_thread_release()`, `ABT_task_retain()`, and `ABT_task_release()`, which have been designed to control refcounts of threads and tasks, have the following issues:
1. Currently, they are broken (i.e., `ABT_thread_release()` does not free a thread even if the counter becomes 0).
2. Fixing it is costly since this adds atomic refcount operations on freeing threads (i.e., `ABT_thread_free()`).
3. These functions are not used in our understanding. At least, they do not appear in our tests.
This PR deprecates these functions. If there's no complaint, they will be removed in the future release.
Note that this patch does not break the current release/retain mechanism; it will just warn programmers:
```
warning: ‘ABT_thread_retain’ is deprecated …
```
> Deprecate ABT_{thread/task}_{retain/release}

- src/include/abt.h.in
- src/stream.c
Unlike `ABT_thread_create()` which delays an execution of thread, `ABT_xstream_create_xxx()` immediately starts an execution stream after creation, so `ABT_XSTREAM_STATE_CREATED` and `ABT_XSTREAM_STATE_READY` are useless.
This PR simplifies the state transition by removing the use of `ABT_XSTREAM_STATE_CREATED` and `ABT_XSTREAM_STATE_READY`; `ABT_xstream_state` can be only either `ABT_XSTREAM_STATE_RUNNING` or `ABT_XSTREAM_STATE_TERMINATED`.
In addition to `ABT_XSTREAM_STATE_CREATED` and `ABT_XSTREAM_STATE_READY`, this change marks `ABT_xstream_start()` as deprecated because a user cannot obtain a handle of an execution stream that has not been started yet. It will be removed in the future release.
> xstream: remove unnecessary ABT_XSTREAM_STATE

- src/include/abti_barrier.h
- src/include/abti_cond.h
- src/include/abti_config.h
- src/include/abti_eventual.h
- src/include/abti_future.h
- src/include/abti_global.h
- src/include/abti_key.h
- src/include/abti_local.h
- src/include/abti_mutex.h
- src/include/abti_mutex_attr.h
- src/include/abti_pool.h
- src/include/abti_rwlock.h
- src/include/abti_sched.h
- src/include/abti_self.h
- src/include/abti_spinlock.h
- src/include/abti_stream.h
- src/include/abti_task.h
- src/include/abti_thread.h
- src/include/abti_thread_attr.h
- src/include/abti_thread_htable.h
- src/include/abti_timer.h
The current naming convention is inconsistent; some use full file names while others use partial ones.
```c
// full file names
abtd_thread.h:
#ifndef ABTD_THREAD_H_INCLUDED
abti_error.h:
#ifndef ABTI_ERROR_H_INCLUDED
// paritial file names
abti_thread.h:
#ifndef THREAD_H_INCLUDED
abti_xstream.h:
#ifndef XSTREAM_H_INCLUDED
```
This PR fixes by using full file names for include guard macros in all headers.
```c
abtd_thread.h:
#ifndef ABTD_THREAD_H_INCLUDED
abti_error.h:
#ifndef ABTI_ERROR_H_INCLUDED
abti_thread.h:
#ifndef ABTI_THREAD_H_INCLUDED
abti_xstream.h:
#ifndef ABTI_XSTREAM_H_INCLUDED
```
> *.h: use full header names for include guards

- src/include/abti.h
- src/include/abti_local.h
- src/include/abti_log.h
- src/include/abti_mem.h
- src/include/abti_mutex.h
- src/include/abti_pool.h
- src/include/abti_self.h
- src/include/abti_stream.h
- src/local.c
- src/log.c
- src/mem/malloc.c
- src/mutex.c
- src/mutex_attr.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
Currently, `ABTI_unit *` is used to distinguish ULTs, tasklets, and external threads, and 'ABTI_xstream *' is used to distinguish ESs and external threads. In both cases, external threads (i.e., Pthreads) do not have an entity of `ABTI_unit` and `ABTI_xstream`, so its `pthread_t` is cast to a pointer type (`ABTI_unit *` and 'ABTI_xstream *') and assigned.
For example, `p_owner` points to either`p_thread/p_task->unit_def` (real `ABT_unit`) or `pthread_t` in the following case.
```c
struct ABTI_mutex_attr {
ABTI_unit *p_owner;
};
int ABT_mutex_lock(...) {
// get local unit
ABTI_unit *p_self;
if (!lp_ABTI_local)              p_self = (ABTI_unit *)pthread_self();
else if(lp_ABTI_local->p_thread) p_self = &p_thread->unit_def;
else if(lp_ABTI_local->p_task)   p_self = &p_task->unit_def;
if …
```
> Use proper ID to distinguish ESs, ULTs, tasklets, and external threads.

- src/include/abt.h.in
- src/info.c
This PR addresses #143 .
Argobots provides no method to programatically know which features are available, though some features such as external thread supports and error checks significantly affect the behavior of Argobots. This is problematic when users cannot control the underlying Argobots implementation, for example, when the shared library is used.
To address this problem, this PR implements a query function, `ABT_info_query_config()`, which returns a configuration parameter of Argobots.
> info: implement a function to query Argobots configuration

- src/arch/abtd_affinity.c
- src/arch/abtd_stream.c
- src/include/abt.h.in
- src/include/abtd.h
- src/stream.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/xstream_revive.c
This PR implements `ABT_xstream_revive()`, a function that restarts an execution stream that has been already joined. This PR addresses #146.
The interface is simple and does not assume that programmers change ES parameters (e.g., main scheduler) on reviving an ES.
```
int ABT_xstream_revive(ABT_xstream xstream);
```
See test/basic/xstream_revive.c to know how to use this function.
This join-revive mechanism uses `pthread_cond`, so it should not be terribly inefficient.
#147, #148, and #149 are prerequisite PRs.
> Add ABT_xstream_revive()

- .travis.yml
- maint/hook/pre-commit
As done by many other projects (including MPICH), Argobots should check the coding style automatically. This PR sets up scripts for Travis CI, which checks trailing white spaces. Note that the original `maint/hook/pre-commit` is that of MPICH (https://github.com/pmodels/mpich/blob/master/maint/hooks/pre-commit).
Specifically, `.travis.yml` executes `maint/hook/pre-commit`, which performs style check by running `maint/code-cleanup.sh`.
The current version of `code-cleanup.sh` is outdated; the future PR should update it.
> Set up Travis CI for style check

- src/arch/abtd_thread.c
- src/barrier.c
- src/cond.c
- src/eventual.c
- src/futures.c
- src/global.c
- src/include/abtd.h
- src/include/abtd_atomic.h
- src/include/abtd_context.h
- src/include/abtd_thread.h
- src/include/abti.h
- src/include/abti_cond.h
- src/include/abti_mem.h
- src/include/abti_mutex.h
- src/include/abti_pool.h
- src/include/abti_spinlock.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/include/abti_thread_htable.h
- src/info.c
- src/key.c
- src/mem/malloc.c
- src/mutex.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_htable.c
The current Argobots has a wrapper for atomic operations but not atomic variables. This makes it vague whether a specific variable should be atomically accessed or not.
```c
struct ABTI_thread {
...
uint32_t request;  // Should this variable be accessed atomically?
uint32_t refcount; // How about this variable?
...
};
void ABTDI_thread_terminate(...) {
[...];
ABTD_atomic_store_uint32(&p_thread->request, ABTI_THREAD_REQ_TERMINATE);
[...];
}
int ABTI_thread_revive(...)
[...];
p_thread->request = 0;  // Can we update it without an atomic operation?
p_thread->refcount = 1; // How about this?
[...];
}
```
To ease the programming, this PR makes atomic operations only work for *atomic-type variables*. Developers need to be aware of atomicity when accessing such an atomic-type variable.
```c …
```
> atomic: force atomic-type variables

- src/error.c
- src/include/abt.h.in
- src/include/abti.h
- src/stream.c
- src/task.c
- src/thread.c
This patch removes deprecated functions, enum constants, and macros.
- Remove deprecated functions
- `ABT_thread_retain()`, `ABT_thread_release()`, `ABT_task_retain()`, `ABT_task_release()`.
- See #138.
- `ABT_xstream_start()`
- See #147
- Remove deprecated constants
- `ABT_XSTREAM_STATE_CREATED` and `ABT_XSTREAM_STATE_READY`
- See #147
- `ABT_ERR_INV_EVENT` and `ABT_ERR_EVENT`
- See #144 
This PR is part of #156
> Remove deprecated functions and constants

- src/cond.c
- src/eventual.c
- src/futures.c
- src/include/abti.h
- src/include/abti_cond.h
- src/pool/fifo.c
- src/pool/fifo_wait.c
Information whether a unit is in a pool or not can be accessed by multiple threads.
https://github.com/pmodels/argobots/blob/master/src/thread.c#L1918
https://github.com/pmodels/argobots/blob/master/src/thread.c#L2321-L2327 
An `ABT_pool`-type variable, `pool`, is used to get this information, but this `pool` is accessed and updated with non-atomic operations, so it can potentially  cause a bug if multithreaded.
This PR simplifies the overall `is_in_pool` mechanism by introducing an `ABT_atomic_int`-type variable, `is_in_pool`. Good things are as follows:
- Atomic acquire/release operations can guarantee completion of pool operations.
- This change reduces the size of `ABTI_unit` by 8 bytes.
- This is demanded to add a new `void *` member variable to implement …
> unit: use is_in_pool instead of pool in ABTI_unit

- src/futures.c
- src/include/abti.h
- test/basic/future_create.c
This PR fixes an implementation of `ABT_future`. Specifically, this PR fixes 
- deadlock issues when errors are found in `ABT_future_wait()` and `ABT_future_set()` and
- functionality of `ABT_future_reset()`.
`ABT_future_reset()` is added to the test `test/basic/future_create.c`.
This fixes #160.
> Fix ABT_future

- configure.ac
- src/arch/fcontext/jump_ppc64_sysv_elf_gas.S
- src/arch/fcontext/take_ppc64_sysv_elf_gas.S
- src/include/abti_thread.h
- src/thread.c
This PR fixes several bugs while checking Argobots on several architectures. This PR includes a workaround that addresses #162.
We tried Argobots tests on x86/64 (Intel Skylake), 64-bit ARM, and IBM POWER9 with several compilers.
```
Intel Skylake:
gnu4.8.5 gnu6.5.0 gnu8.3.0 gnu9.2.0 clang3.9.1 clang7.0.1 clang9.0.0, icc18.1, icc19.4
64-bit ARM:
gnu4.8.5 gnu6.5.0 gnu8.3.0 gnu9.2.0 clang3.9.1 clang7.0.1 clang9.0.0
IBM POWER9
gnu4.8.5 gnu6.5.0 gnu8.3.0 gnu9.2.0 clang3.9.1 clang7.0.1 clang9.0.0, xlc16.1.1
```
Checked configuration options include:
```
(default arg),
--enable-perf-opt
--enable-debug=yes
--enable-debug=all
--enable-feature=no / randomly chosen
--enable-checks=no / randomly chosen
--disable-simple-mutex
--enable-affinity
```
All combinations above with all the supported …
> Fix miscellaneous bugs

- configure.ac
- src/arch/fcontext/jump_arm64_aapcs_elf_gas.S
This PR implements `init_and_call_fcontext` for `arm64-elf`, which is a key assembly function for dynamic promotion technique (#72).
Now `x86_64-elf` and `arm64-elf` support the dynamic promotion technique.
It passed all the tests on an ARM machine.
> Implement a dynamic promotion thread for ARM64.

- configure.ac
- src/arch/fcontext/jump_ppc64_sysv_elf_gas.S
This PR implements `init_and_call_fcontext` for `ppc64-elf` (i.e., POWER architecture), which is a key assembly function for dynamic promotion technique (#72).
Now the dynamic promotion technique support major CPU architectures used in HPC (x86/64, ARM, and POWER).
It passed all the tests on a POWER8 (`ppc64le`) machine.
PR #87 and #91 are prerequisite.
> Implement a dynamic promotion thread for 64-bit POWER

- src/include/abt.h.in
- src/stream.c
`ABT_xstream_set_rank()` was declared as follows, but the const qualifier to a scalar-type argument is meaningless.
```c
int ABT_xstream_set_rank(ABT_xstream xstream, const int rank);
```
This change keeps the same function type, so it won't break the compatibility; for example, the following is allowed (without any compiler warning) as far as I checked.
```c
int ABT_xstream_set_rank(ABT_xstream xstream, int rank); // no const
void func() {
typedef void (*old_fn_type)(ABT_xstream, const int); // const here
old_fn_type fn_type = ABT_xstream_set_rank; // no warning
}
```
> abt.h: remove unnecessary const

- src/global.c
- src/include/abti.h
- src/stream.c
This PR implements `ABTI_xstream_init_main_sched()`, an initialization-only version of `ABTI_xstream_set_main_sched()`. Since this does not take `ABTI_local **`, this change enables `ABTI_xstream_create()` and `ABTI_xstream_create_primary()` to remove an argument of `ABTI_local **`. The new function types of `ABTI_xstream_create_XXX()` are very natural since these functions never context switch.
This is just an internal cleanup and incurs no visible performance difference.
> Add ABTI_xstream_init_main_sched()

- src/include/abti_log.h
- src/local.c
- src/log.c
- src/stream.c
Although `ABTI_log` functions are for debugging, they do not work because of SEGV when  `lp_local == NULL` and `lp_ABTI_log == NULL`. The log interface should be robust so that it can be used everywhere. This PR fixes it.
Note that there is no performance impact if a user does not explicitly set `--enable-debug=log` or stronger; even with this option, there should not be performance difference.
> Robust logging

- src/include/abti_mem.h
- src/thread_attr.c
This PR fixes small issues and cleans up `ABTI_mem_alloc_thread()`.
The following code does not reset a "stack" variable in `ABTI_thread_attr`. This PR fixes it.
```c
ABT_thread_attr_set_stack(attr, stack, stacksize1);
ABT_thread_attr_set_stack(attr, NULL, stacksize2);
// Since NULL is set here, p_stack should be internally updated
```
The following code tries to access a local memory pool, which causes SEGV. This PR fixes it.
```c
external_thread():
ABT_thread_attr attr;
ABT_thread_attr_create(&attr); // attr is initialized.
ABT_thread_create(..., attr, ...);
```
This slightly simplifies the complicated branch in `ABTI_mem_alloc_thread()`. This also compensates the additional branch added by 2.
They are not performance critical, so the performance difference is not visible.
> Miscellaneous thread allocation fixes

- src/include/abti_mem.h
- src/include/abtu.h
- src/mem/malloc.c
- src/util/Makefile.mk
- src/util/largepage.c
This PR applies code refactoring to `malloc.c` and `abti_mem.h`.
1. Create `ABTU_xxx_largepage()` functions and use them in `malloc.c`.
- `malloc.c` does not need to handle detailed `mmap` options, which are now handled in `util/largepage.c`.
2. Clean up control flow in `ABTI_mem_alloc_thread()`
- The current code is too complicated to understand which path is finally taken with a certain situation (e.g., default vs explicit MEMPOOL under external threads). This PR fixes it, though it makes the code a bit longer.
The logic will not be changed by this PR.
> Memory code cleanup

- src/arch/abtd_thread.c
- src/include/abti.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
This PR fixes small issues in `ABTI_sched` implementation.
-  Use a linked list instead of an array of `ABTI_sched`. A linked list is simpler and does not require additional memory allocation.
- Rename `is_sched` to `p_sched` since it is actually of `ABTI_sched *` type.
This PR is for cleanup and does not affect the performance.
> Miscellaneous scheduler cleanup

- src/arch/abtd_thread.c
- src/global.c
- src/include/abtd_thread.h
- src/include/abti.h
- src/include/abti_log.h
- src/include/abti_thread.h
- src/log.c
- src/mutex.c
- src/sched/sched.c
- src/stream.c
- src/thread.c
- src/thread_htable.c
In Argobots, a scheduler (`ABTI_sched`) is treated like a first-class schedulable work unit though its underlying implementation is either a ULT or a tasklet. This work unit type creates a weird context called *a scheduler context*, which is visible to users in a user-defined scheduler. As mentioned in #170, this scheduler context is restricted by the underlying implementation (i.e., ULT or tasklet), but also has its own semantics (e.g., `ABT_self_xxx()` is disallowed). In the Argobots runtime, this scheduler handling is a mess (e.g., `ABTI_LOG_SET_SCHED()`).  Since essentially a scheduler is (and should be) a ULT in terms of threading capabilities, we should narrow this gap as much as possible.
This PR does not fix all the issues, but it removes most part of special handling for …
> sched: narrow the gap between scheduler and thread

- src/arch/abtd_thread.c
- src/include/abti.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/log.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
The current implementation allows a tasklet-type stackable scheduler, which is very restrictive in terms of functionality though it can reduce only little overheads since basically schedulers are not invoked frequently. 
This PR modifies a tasklet-type stackable scheduler to use a ULT internally, while it keeps the external interface that allows users to specify a tasklet type (i.e., Argobots still accepts `ABT_SCHED_TYPE_TASK`). It can simplify the implementation in Argobots.
Note that this does not break the existing API and its semantics since previously there was no way for users to get an underlying work unit implementation in a scheduler context.
> sched: use a ULT for a tasklet-type stackable scheduler

- src/arch/abtd_thread.c
- src/global.c
- src/include/abti_log.h
- src/include/abti_mutex.h
- src/include/abti_pool.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/log.c
- src/mutex.c
- src/pool/pool.c
- src/sched/randws.c
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_htable.c
Argobots has two logging interface: `LOG_EVENT()` and `LOG_DEBUG()`.
- `LOG_EVENT()` prints an event message. It prints the information of the underlying execution stream and ULT/tasklet in addition to the event message.
- `LOG_DEBUG()` prints a debug message. It prints the information of `__FILE__` and `__LINE__` in addition to the event message.
Those two are very similar and both are used primarily for debugging (since these logging interface is quite heavy). However, they are controlled by different environmental variables (`ABT_USE_LOG` and `ABT_USE_DEBUG`), which is confusing.
This PR removes `LOG_EVENT()` and uses `LOG_DEBUG()` instead. The implementation of `LOG_DEBUG()` is actually replaced by that of `LOG_EVENT()`, however, since `LOG_EVENT()` prints more useful information. The …
> log: replace LOG_EVENT() with LOG_DEBUG() 

- src/arch/fcontext/make_ppc64_sysv_elf_gas.S
`make_fcontext()` did not save `FPSCR` and `VSCR`, so threads resumed by `jump_fcontext()` or `take_fcontext()` restored invalid `FPSCR` and `VSCR`. This sometimes makes results of floating operations wrong.
I saw this issue in a vectorized program (with VSX) on POWER 9, but it may happen in a non-vectorized program on other POWER architectures.
This PR fixes it.
> fcontext: fix ppc64 assembly code

- src/include/abti_mem.h
- src/mem/malloc.c
`--disable-mem-pool` disables the memory pool optimizations in Argobots, but the current Argobots cannot be compiled with this option since it has been overlooked for a while. This PR fixes this issue.
`--disable-mem-pool` is added to Jenkins tests (as one of the random configurations), so this option will be tested regularly.
Note that this option is useful if one uses an external scalable memory allocator (e.g., tcmalloc and jemalloc).
> mem: fix memory allocation code when the memory pool is disabled

- src/include/abti.h
- src/stream.c
- src/thread.c
This PR simplifies the current thread migration code, which is complicated and costly.
This PR does not change the current API/ABI. This change should improve the performance if the migration feature is used; otherwise there should be no visible performance difference.
> Cleanup thread migration code

- src/include/abti.h
- src/sched/sched.c
- src/stream.c
- src/thread.c
This PR removes the complicated synchronization code behind `ABT_thread_migrate_to_sched()`, `ABT_thread_migrate_to_xstream()`, and `ABT_thread_migrate()`.
`ABT_thread_migrate_to_sched()`, `ABT_thread_migrate_to_xstream()`, and `ABT_thread_migrate()` basically find a pool of the running scheduler (associated with the given execution stream) and creates a request of migration to the pool. The request is attached to a ULT since that ULT might be being scheduled by a scheduler. A scheduler who finds a request attached to a ULT will migrate this ULT to the target pool.
Obviously, all the involving objects must be alive during the process (i.e., the target pool may not be freed while a thread is being migrated). This is actually hard to guarantee from the runtime perspective. The current …
> Simplify thread migration logic

- src/arch/abtd_thread.c
- src/global.c
- src/include/abti.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/sched/sched.c
- src/stream.c
- src/task.c
- src/thread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/sched_on_thread.c
This patch enables `ABT_xstream_schedule_unit()` on a non-scheduler ULT. This is a large change because this PR essentially provides a way to implement a scheduler without `ABT_sched`.
Specifically, this allows a normal ULT to "directly" schedule ULTs and tasklets by combining `ABT_pool_xxx()` and `ABT_xstream_schedule_unit()` while, for example, waiting for something. From another viewpoint, one can make a scheduler that can also work as a normal ULT (e.g., calling a barrier etc).
This feature should be useful to implement a complicated scheduler, for example, a parallel work unit that does both scheduling and computation. For example, OpenMP thread is a scheduler of OpenMP tasks (belonging to that parallel region) but can perform computation (e.g., `#pragma omp for`).
Internally, this …
> thread: allow ABT_xstream_schedule_unit() on a normal ULT

- examples/stencil/stencil_forkjoin_divconq_hrws.c
- Issue: `alloca.h`
The required header for `alloca()` is system dependent.  For example, `alloca()` needs `alloca.h` on Linux while `stdlib.h` is needed on FreeBSD.  An example implementation should be portable. Just use `malloc()`.
> Support FreeBSD

- src/include/abt.h.in
- src/include/abti.h
- src/self.c
- test/benchmark/init_finalize.c
- test/benchmark/task_fork_join.c
- test/benchmark/thread_fork_join.c
This PR fixes miscellaneous issues in Argobots. All of them do not affect the performance.
@mdorier reported the second issue (`ABT_UNIT_TYPE_XSTREAM` and `ABT_UNIT_TYPE_EXT`). Thank you!
> Miscellaneous fixes

- src/arch/abtd_env.c
- src/include/abti.h
- src/key.c
It is related to #159.
This PR optimizes the current `ABT_key` mechanism. Specifically, this PR removes the following:
- Modulo (`%`)
- A reference counter (`refcount`) that is atomically incremented/decremented.
This PR also cleans up `src/key.c`.
> key: optimize ABT_key operations

- configure.ac
- src/include/abti.h
- src/include/abti_mem.h
- src/include/abtu.h
- src/key.c
- src/mem/malloc.c
- src/task.c
- src/thread.c
- test/basic/task_data.c
- test/basic/thread_data.c
This PR, with #196, fixes #159.
Too many `malloc()` in `ABT_key` operations significantly degrade the performance, discouraging users from using the `ABT_key` interface.
`malloc()` is replaced by a generic memory pool introduced by #183. This memory pool is shared with the task descriptor pool, so it does not increase the memory footprint (and does not overly make the current memory pool management).
The following shows the overhead [ns] of `ABT_key` operations on 56-core (2-socket Intel Xeon Platinum 8180 Processor). Lower is better. The blue one is before the optimization of #196, the orange bar is the current master (#196), and the gray one is this PR. Basically each ES forks and joins 256 threads (=ULTs) in total, while each ULT accesses the TLS several times. Striped bars mean a …
> key: use memory pool for allocation

- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_key.h
- src/include/abti_unit.h
- src/key.c
- src/task.c
- src/thread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/task_data2.c
- test/basic/thread_data2.c
This addresses #198; it would be nice to have TLS functions that can be accessed by not only the owner (=self) but also other parallel units as well.
This PR implements the following functions:
```c
int ABT_thread_set_specific(ABT_thread thread, ABT_key key, void *value);
int ABT_thread_get_specific(ABT_thread thread, ABT_key key, void **value);
int ABT_task_set_specific(ABT_task task, ABT_key key, void *value);
int ABT_task_get_specific(ABT_task task, ABT_key key, void **value);
```
These functions take a work unit handle, so these functions can access other's TLS.
It degrades the performance of `ABT_key` access since atomic operations are newly added in some paths. In Argobots, a key table and its element of a key table are lazily created, so synchronization is necessary if two parallel …
> key: extend get/set_specific interface

- Doxyfile.in
- maint/hook/pre-commit
- src/info.c
- test/basic/eventual_test.c
- test/basic/info_stackdump2.c
- test/basic/sched_randws.c
- test/basic/thread_self_suspend_resume.c
- test/benchmark/task_fork_join.c
- test/benchmark/thread_fork_join.c
This PR updates some terms in the Argobots code.
We also change the default branch of Argobots to `main`; we will keep `master` updated for a week or so but plan to remove the branch after that.
> Remove inappropriate terms in the code

- src/include/abt.h.in
- src/include/abti_stream.h
- src/self.c
- src/task.c
- src/thread.c
This patch adds utility functions that check if a given work unit is unnamed (or anonymous) or not.
```c
int ABT_thread_is_unnamed(ABT_thread thread, ABT_bool *flag);
int ABT_task_is_unnamed(ABT_task task, ABT_bool *flag);
int ABT_self_is_unnamed(ABT_bool *flag);
```
They should be useful in general, but they are needed specifically for #199 (precisely speaking, for tool tests) because a state transition pattern of a named work unit is different from that of an unnamed work unit (e.g., no "join").
> thread/task: add functions to check if a work unit is unnamed

- configure.ac
- src/Makefile.am
- src/arch/abtd_thread.c
- src/barrier.c
- src/cond.c
- src/eventual.c
- src/futures.c
- src/global.c
- src/include/Makefile.mk
- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_cond.h
- src/include/abti_error.h
- src/include/abti_mutex.h
- src/include/abti_thread.h
- src/include/abti_tool.h
- src/info.c
- src/mutex.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_htable.c
- src/tool.c
- test/util/abttest.c
- test/util/abttest.h
Now Argobots does not provide any interface to check the internal state, so it is hard to profile or debug Argobots without modifying the Argobots runtime. As done by MPI and OpenMP (e.g., PMPI and OMPT), Argobots should expose a similar interface. A profiling interface (or, actually a profiling tool) has been demanded by several users (recently from @roblatham00), it would be nice to implement such now.
Argobots provides an interface ("tool interface") to register callback functions, which are called on several threads and tasklets events (e.g., creation, run, join, yield, ... ). The interface is work-unit centric, so with this feature, users can know  avg/max/min execution time of threads (i.e., thread granularity), number of yields and suspensions, delay of scheduling (i.e., time of …
> add a tool interface for profiling

- examples/profiling/.gitignore
- examples/profiling/Makefile.am
- examples/profiling/abtx_prof.h
- examples/profiling/async_engine.c
This PR adds a new profiling example, `async_engine`, with some new features.
This example implements a small asynchronous event/task/request engine. The primary execution stream creates several "operations" (e.g., network or I/O operations in real use cases) associated with ULTs.  These ULTs are executed by multiple secondary execution streams.
With `ABTX_PROF_ASSUME_SCHED_ALWAYS_ACTIVE=0`, ABTX profiler measures the actual execution time that excludes time not scheduled by OS. It can happen if Pthreads are oversubscribed or schedulers employ sleeping mechanism (e.g., `ABT_pool_pop_wait()`).
For example, you create one event issuer and one event engine. If there is not much work (in this case, only 200 operations per second and each operation costs 360 microseconds), the event engine is …
> examples/profiling: add a new example, async_engine

- configure.ac
- examples/profiling/abtx_prof.h
- examples/stencil/stencil_depend_yield.c
- src/include/abtd.h
- test/basic/info_stackdump.c
- test/basic/info_stackdump2.c
- test/basic/sched_on_thread.c
- test/util/abttest.h
PGI 20.x is sufficiently modernized so now it can compile Argobots. This PR fixes minor issues to enable PGI to compile Argobots. Argobots + PGI compiler will be tested regularly.    
Note that Argobots does not work with older PGI compiler (-19). If your program needs an old PGI compiler, please link your program to the Argobots library already compiled by another compiler (e.g., GCC).
> support PGI compiler

- src/include/abti_thread_attr.h
- src/thread_attr.c
We do not maintain doxygen comments for private functions (e.g.,`ABTI_*`).  To be consistent, a few existing comments for `ABTI_` functions should be removed.
> doxygen: remove doxygen comments for private functions

- src/thread.c
This PR fixes a bug in `ABT_thread_create_many()`.
`ABT_thread_create_many()` passes `NULL` to `ABTI_thread_create_internal()`'s `pp_newthread` when it needs to create an unnamed ULT while `pp_newthread` may not be `NULL`. This PR fixes it.
> thread: fix a bug in creation of multiple unnamed ULTs

- test/basic/eventual_create.c
- test/basic/init_finalize.c
- test/basic/rwlock_reader_incl.c
- test/basic/sched_on_thread.c
- test/basic/task_data.c
- test/basic/thread_data.c
This PR fixes memory leaks in `test/basic`. Note that this bugs are not in the Argobots library but in the test programs.
> test/basic: fix memory leaks

- src/arch/Makefile.mk
- src/arch/abtd_affinity.c
- src/arch/abtd_affinity_parser.c
- src/arch/abtd_env.c
- src/include/abtd.h
- src/stream.c
Core binding of execution streams could not be easily set via an environmental variable; the current Argobots allows only either assigning ES-n to CPU-n or no affinity.  `ABT_xstream_set_affinity()` allows complicated affinity settings, but it is tedious.
This PR extends `ABT_SET_AFFINITY`.  `ABT_SET_AFFINITY=XXX` allows detailed affinity description including multiple cores per ES and a strided pattern.  Note that this PR does not change the existing behavior.
The grammar is similar to that of Open MP (`OMP_PLACES`), but slightly different.  The specific grammar is as follows (or please see `src/arch/abtd_affinity.c`).
The Argobots affinity module parses the following grammar while it ignores all white spaces between tokens.  Double-quoted symbols in the following are part of the syntax. …
> enrich affinity interface

- maint/code-cleanup.sh
code-cleanup.sh with the latest `clang-format` (e.g., `clang-format-10`) breaks the current format rule since it treats named arguments of GCC inline assembly differently (precisely speaking, different from `clang-format-6.0`, which is the coding standard of Argobots at present).
```diff
-                         : [pv0] "+&r"(prev0), [pv1] "+&r"(prev1),
+                         : [ pv0 ] "+&r"(prev0), [ pv1 ] "+&r"(prev1),
```
This PR fixes it by adding a new format option.
> maint: update code-cleanup.sh

- src/include/abti_mutex.h
- src/mutex.c
With a weak compare-and-swap operation, mutex lock can spuriously fail, which causes counterintuitive phenomena.  Specifically, `ABT_mutex_lock()` internally yields although no thread is hold a lock.
For example, `test/basic/cond_signal_in_main.c` failed because of this bug:
https://github.com/pmodels/argobots/blob/c01b4b0d2c2f8e9f1bd9900d23485ba971fc1a21/test/basic/cond_signal_in_main.c#L18
In this test code, only one execution stream is used, so the schedule is deterministic (at least that is what users expect), but `ABT_mutex_lock()` sometimes fails on some architectures (we found this bug on POWER9 with GCC10) because internal `ABTD_atomic_bool_cas_weak_uint32()` spuriously fails. This extremely rare scheduling change causes a deadlock on POWER9.
This patch fixes this issue by using …
> mutex: use strong compare-and-swap for mutex lock operations

- configure.ac
- src/include/abti.h
- src/include/abti_key.h
- src/include/abti_stream.h
- src/info.c
- src/key.c
- src/log.c
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/thread.c
This PR refactors code for a stackable scheduler. As a result, a stackable scheduler can be always enabled without performance loss.
Note that a stackable scheduler was enabled by default, so this change does not affect most users (except for small overhead reduction).
> Always enable the stackable scheduler feature

- src/global.c
- src/include/abti.h
- src/include/abti_mem.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/include/abti_unit.h
- src/log.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
This PR embeds `refcount` and `migratable` in `ABTI_unit_type`. This can make the struct size of `ABTI_unit` smaller. This change is necessary for the future commit.
This PR does affect the existing code.
> unit: embed refcount and migratable

- src/include/abti.h
- src/include/abti_key.h
- src/include/abti_unit.h
- src/key.c
- src/stream.c
- src/task.c
- src/thread.c
This PR refactors the migration feature. Specifically, this PR removes `f_migration_cb`, `p_migration_cb_arg`, and `p_migration_pool` from `ABTI_pool`. This is mainly for code cleanup.
Note that this PR does not change the functionality but degrades the performance of migration while slightly reducing the overheads of ULTs overall. I believe the migration feature is rarely used and, even if it is used, not performance critical. Nevertheless, if one heavily uses this feature, please let us know so that we can optimize the migration feature.
> Refactor the migration feature

- configure.ac
- src/include/abtu.h
- src/log.c
- src/util/util.c
- test/Makefile.mk
Only `ABTU_get_int_len()` uses on a math library in Argobots, but this function is not very necessary.  This patch removes it.
Note that it can remove the math library dependency (`-lm`) from Argobots.
> util: remove ABTU_get_int_len()

- src/include/abtd_ythread.h
- src/include/abti.h
- src/include/abti_mem.h
- src/include/abti_thread_attr.h
- src/mem/malloc.c
- src/task.c
- src/thread.c
- src/thread_attr.c
This patch improves functions called in `ABTI_thread_create()` and `ABTI_thread_free()`.
Note that `sizeof(ABTI_ythread)` on most architectures including x86/64, POWER9, and 64-bit ARM becomes 128 bytes after this patch (*if `fcontext` is enabled, a compiler is GCC compatible in terms of structure alignment, and the pointer size is 8 bytes (64-bit OS)).
> thread: improve ABTI_thread_create() and ABTI_thread_free()

- src/barrier.c
This PR fixes a bug introduced by #238.
> barrier: fix a memory bug in ABT_barrier_reinit()

- src/arch/abtd_ythread.c
- src/global.c
- src/include/abti.h
- src/include/abti_sched.h
- src/include/abti_stream.h
- src/include/abti_tool.h
- src/include/abti_ythread.h
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/thread.c
- src/tool.c
- src/ythread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/main_sched.c
- test/basic/xstream_rank.c
- test/util/abttest.c
Main schedulers are running on yieldable `ABTI_thread`, but they cannot yield because these schedulers do not have parent threads. Main schedulers, therefore, cannot run synchronization operations that might call yield; for example, main schedulers cannot call `ABT_mutex_lock()`, `ABT_thread_yield()` and `ABT_thread_join()`.
This restriction was not clearly explained.  Some functions return an error code while others silently cause a fatal error.  For proper error handling, this behavior must be clarified.
This PR introduces a root thread that schedules a main scheduler.  This fix makes all the user-visible "ULT"-based threads (or yieldable-threads, or user-visible `ABTI_ythread`) truly yieldable.  This fix cleans up some existing code as well.
Nonetheless, users are not recommended to …
> xstream: introduce a root thread

- src/include/abtu.h
- src/util/Makefile.mk
- src/util/util.c
This patch works around the issue reported in https://github.com/pmodels/argobots/issues/244 by adding a special path for IBM XLC. We can remove it once XLC addresses this issue. I have already confirmed that this solves the issues on POWER9 with XLC 16.1.1.
Note that this does not affect the performance if the other compilers are used.
> work around XLC compilation bug

- src/pool/pool.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
- src/timer.c
- test/basic/self_type.c
Some Argobots functions return errors for several reasons.  On failure, most Argobots function do not modify values including the Argobots' internal values and arguments given by the user.  This atomic behavior is reasonable: every function should either complete an operation or return an error without any side effect.
A few functions, however, update user-given arguments, which violates this policy and makes the behavior of Argobots functions inconsistent.  For example, `ABT_thread_create()` sets `*thread = ABT_THREAD_NULL` if it is called on any type of failure (e.g., memory allocation failure or calling `ABT_thread_create()` before `ABT_init()`) while `ABT_mutex_create()` does not (`*mutex` will not be modified).  Obviously, Argobots should not modify values on failure; otherwise, it …
> error: do not update a variable on failure

- src/sched/sched.c
`ABT_sched`'s `p_data` is not initialized in `ABT_sched_create()`, so `ABT_sched_get_data()` returns an uninitialized value.  This behavior is not intuitive for most users.  Since scheduler creation is not performance critical, this PR initializes `p_data` to NULL on creation.
> sched: initialize p_sched->p_data

- maint/version.m4
This PR fixes the ABI string, which has not been updated in the release 1.0 by mistake.
> maint: fix ABI string

- src/barrier.c
`ABT_barrier` might be freed right after `ABT_barrier_wait()`.  `lock` is taken in `ABT_barrier_free()` in order not to free `ABT_barrier()` that is being used.  The number of waiters, however, is checked **before** this lock, which causes an error if `assert()` is enabled; before taking `lock`, there might exist some waiters.
This PR fixes it by checking the number of waiters **after** taking `lock`.
> barrier: fix ABT_barrier_free

- src/arch/abtd_env.c
- src/include/abti_key.h
- src/include/abti_mem.h
- src/include/abtu.h
- src/mem/malloc.c
- src/stream.c
It is sometimes hard to understand the intension of the code without math functions.  Basic math functions improve readability.
```c
// min
if (p_global->thread_stacksize * ABTD_MEM_MAX_NUM_STACKS
> ABTD_MEM_MAX_TOTAL_STACK_SIZE) {
mem_max_stacks = ABTD_MEM_MAX_TOTAL_STACK_SIZE / p_global->thread_stacksize;
} else {
mem_max_stacks = ABTD_MEM_MAX_NUM_STACKS;
}
// =>
mem_max_stacks = min(ABTD_MEM_MAX_TOTAL_STACK_SIZE / p_global->thread_stacksize,
ABTD_MEM_MAX_NUM_STACKS);
// roundup
size_t stacksize = (thread_stacksize + sizeof(ABTI_ythread)
+ ABT_CONFIG_STATIC_CACHELINE_SIZE - 1) &
(~(ABT_CONFIG_STATIC_CACHELINE_SIZE - 1));
// =>
size_t stacksize = roundup(thread_stacksize + sizeof(ABTI_ythread),
ABT_CONFIG_STATIC_CACHELINE_SIZE);
```
Note that these functions are typed (i.e., not macros), …
> util: introduce basic math functions

- src/arch/abtd_env.c
- src/include/abti.h
- src/include/abti_key.h
- src/include/abtu.h
- src/info.c
- src/util/Makefile.mk
- src/util/atoi.c
Argobots reads environment variables without checking if values are in an acceptable range.  
Although passing such a large value (e.g., 4GB for page size) is not practical,, some variable type are improper to read and store these values: `int` and `uint32_t` are used for data size. Values are read by 'atoi()' and `atol()`, so they might fail to read big unsigned values.
This PR cleans up the code in `ABTD_env_init()`; it fixes type issues and uses new `atoi()` functions that can handle overflow.
> env: improve reading process of Argobots' environment variables

- test/basic/error.c
#261 introduced c90-incompatible code by mistake. This PR fixes it.
> test/basic: fix error test to comply with c90

- examples/profiling/abtx_prof.h
Solaris compiler 12.5 does not support `__builtin_expect()` by default, so it causes a compilation error. This PR fixes it.
> examples/profiling: do not use __builtin_expect with Solaris 12.5

- examples/profiling/abtx_prof.h
- src/arch/abtd_affinity.c
- src/arch/abtd_affinity_parser.c
- src/arch/abtd_env.c
- src/barrier.c
- src/error.c
- src/eventual.c
- src/futures.c
- src/include/abtd.h
- src/include/abtd_atomic.h
- src/include/abti.h
- src/include/abti_mem_pool.h
- src/include/abti_ythread_htable.h
- src/info.c
- src/mem/mem_pool.c
- src/mutex.c
- src/sched/sched.c
- src/stream.c
- test/basic/error.c
- test/basic/sched_set_main.c
- test/benchmark/task_ops_all.c
- test/benchmark/thread_ops_all.c
Some C compilers (e.g., `pgcc`) are based on C++ behavior, so they warn singed/unsigned comparison everywhere. This PR fixes this signed/unsigned comparison because 1.  this is very annoying and 2. signed/unsigned should be managed properly even if C allows mixing them.
Specifically, this PR explicitly casts arguments and changes types of variable to fix this warning. To check this warning with GCC/Clang, you need to explicitly pass `-Wsign-compare`.
This PR should not affect the performance of Argobots.
> fix signed/unsigned warning

- src/eventual.c
- src/include/abt.h.in
- test/basic/eventual_create.c
`ABT_bool` should be used for the `is_ready` argument of `ABT_eventual_test()`, which was `int`.  This PR fixes it.
```c
// Old definition
int ABT_eventual_test(ABT_eventual eventual, void **value, int *is_ready);
// New definition
// typedef int ABT_bool;
int ABT_eventual_test(ABT_eventual eventual, void **value, ABT_bool *is_ready);
```
Note that currently `ABT_bool` is `int`, so it does not cause any ABI compatibility issue.
> eventual: use ABT_bool for ABT_eventual_test()

- src/arch/abtd_stream.c
- src/include/abt.h.in
- src/include/abtd.h
- src/info.c
- src/sched/sched.c
- src/stream.c
- src/thread.c
- src/ythread.c
This PR improves `ABT_info` functions:
1. Update the contents printed by info functions.
- `ABT_info_print_all_xstreams()`, `ABT_info_print_xstream()`, `ABT_info_print_sched()`, `ABT_info_print_pool()`, and `ABT_info_print_thread()`.
2. Make some info  functions runnable before `ABT_init()`
- `ABT_info_query_config()`, `ABT_info_print_config()`, and `ABT_info_print_all_xstreams()`
- This is useful to check if the underlying Argobots supports necessary configure-time features before `ABT_init` (e.g., `support of external threads`).
3. Make some info functions accept NULL handles
- For example, `ABT_info_print_thread()` prints `"THREAD NULL"` instead of returning an error when `ABT_THREAD_NULL` is passed.
4. Minor fixes and improvements
- Fix the condition of FPU preservation.
- Add a query …
> improve ABT_info functions

- src/include/abti.h
- src/include/abti_stream_barrier.h
- src/stream_barrier.c
`ABT_stream_barrier` was unavailable if `pthread_barrier` is not supported. Although such a case should be extremely rare, we should provide the same functionality if it should happen.  This patch implements a simple sense-based barrier implementation (though it uses `uint64`-type tag instead of `bool`-type sense).  See https://en.wikipedia.org/wiki/Barrier_(computer_science) for details.
Note that `ABT_stream_barrier` uses `pthread_barrier` by default, so this PR will not affect execution on almost all platforms.
> stream_barrier: add a fallback implementation of ABT_stream_barrier

- configure.ac
- src/arch/fcontext/jump_x86_64_sysv_elf_gas.S
- src/include/abt.h.in
- src/include/abtd_context.h
- src/include/abtd_fcontext.h
- src/include/abtd_ucontext.h
- src/include/abti_ythread.h
- src/info.c
- src/ythread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/info_print_stack.c
This PR implements a stack unwinding feature in Argobots. This PR should address #101 pointed out by @bfaccini .
This stack unwinding feature is for debugging. Specifically, this feature enables a user to dump thread information including ULTs in pools in a more user-friendly manner.
1. Configure Argobots with libunwind (I checked this with libunwind-1.4.0, but it should work with LLVM's libunwind).
```sh
./configure --with-libunwind=LIBUNWIND_INSTALL_PATH --enable-stack-unwind
```
2. Run `ABT_info_print_thread_stack_unwind()` or `ABT_info_trigger_print_all_thread_stacks()`
See https://github.com/shintaro-iwasaki/argobots/blob/supportlibunwind/test/basic/info_stack_unwind.c .
It will print the following (`ABT_info_trigger_print_all_thread_stacks()`), where `thread_func` is a user …
> info: support stack unwinding

- src/thread_attr.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/thread_attr2.c
`ABT_thread_attr_set_stacksize()` does not respect a given stacksize; ULTs always use a predefined stacksize.
Specifically, this `ABTI_THREAD_TYPE_MEM_MEMPOOL_DESC_STACK` should be `ABTI_THREAD_TYPE_MEM_MEMPOOL_DESC` in the following commit
https://github.com/pmodels/argobots/commit/83384c12582b7d46804b392a3617e2467d269c65#diff-6f9f49a603098ca4eb0f081a78c2b958f1361e852751d5353b8d332a5e755f66R191
Argobots did not have a test to check a real stack size assigned to ULTs, making this issue overlooked.
This PR fixes `ABT_thread_attr_set_stacksize()`. The assigned stack is tested by `test/basic/thread_attr2`.
> thread_attr: fix ABT_thread_attr_set_stacksize

- Doxyfile.in
- examples/profiling/abtx_prof.h
- src/global.c
- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_tool.h
- src/thread.c
- src/tool.c
- test/util/abttest.c
This PR updates the specification of the current tool API for the upcoming Argobots 1.1
Specifically, this PR merges the two versions of tool functions for a ULT and a tasklet into one to make the API simpler. The user should use `ABT_tool_register_thread_callback` for tasklet profiling.
The tool interface is not included in Argobots 1.0, so this change should not break any API and ABI compatibility. By default the tool interface is disabled, so it will not affect the performance of most applications.
> tool: API clean up

- Doxyfile.in
- configure.ac
- src/include/abt.h.in
- src/include/abti_thread.h
- src/info.c
This PR updates the specification of the current info API for the upcoming Argobots 1.1.
Specifically, this PR restores the old error checks that existed in Argobots 1.0 for the backward compatibility. This PR itself does not hurt the performance. Unless the user program highly relies on the error code (not an error, an "error code"), this PR does not affect the behavior of the program.
> info: improve API

- Doxyfile.in
- src/global.c
- src/include/abt.h.in
- src/include/abti.h
- src/self.c
- src/stream.c
- src/thread.c
- test/basic/self_type.c
This PR improves the API and its explanation of `ABT_self_xxx()` functions for the upcoming Argobots 1.1.
This PR does not change the API of Argobots 1.0 except for the following "bug".
* `ABT_self_suspend()`: it returns `ABT_ERR_INV_XSTREAM` if it is called by an external thread.
In Argobots 1.0, it returns `ABT_ERR_INV_THREAD` in such a case. I believe it is a bug, not an intended error code (for some particular reasons). Note that all the functions in Argobots return `ABT_ERR_INV_XSTREAM` when an external thread wrongly calls a routine.
Because Argobots-1.0 compatible error check is slightly heavier, some `ABT_self_xxx()` functions might be slightly slower (say, five cycles or so), but overall I don't think this change affect any program.
This PR also replaces "main ULT" with "primary …
> self: improve API

- Doxyfile.in
- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_error.h
- src/pool/pool.c
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/config.c
- src/sched/prio.c
- src/sched/randws.c
- src/sched/sched.c
- src/stream.c
- test/basic/sched_prio.c
This PR improves the API and its explanation of `ABT_sched_xxx()` (including `ABT_sched_config_xxx()`) functions for the upcoming Argobots 1.1.
This PR does not change the API of Argobots 1.0 except for the following "behavior".
- `ABT_sched_type`: regardless of this value, the runtime will always create a ULT-type scheduler. A tasklet-type scheduler is too restrictive and the runtime cannot support it. Note that this change has been already adopted by #182.
- `ABT_sched_config_access`: regardless of this value, the runtime will always create a MPMC-type pool for a `ABT_POOL_NULL` pool. This is because non-MPMC pools are too restrictive (e.g., regarding a resume operation). The user can manually create such a pool by `ABT_pool_create_basic()`.
This PR also fixes some bugs (e.g.,  memory …
> sched: improve API

- Doxyfile.in
- examples/scheduling/sched_and_pool_user.c
- src/include/abt.h.in
- src/include/abti.h
- src/info.c
- src/log.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/basic_wait.c
- src/stream.c
- src/task.c
- src/thread.c
- src/unit.c
This PR improves the API and its explanation of `ABT_pool_xxx()` functions for the upcoming Argobots 1.1.
The changes of this PR are relatively larger than the others, but this PR does not affect the behavior of a program (much) if a program does not use user-defined pools. In other words, unless your program uses `ABT_pool_create()` (*not `ABT_pool_create_basic()`*), these API changes are almost negligible.
- `ABT_pool_access`: the Argobots runtime uses access only to determine the pool implementation.
It has been already removed by #239, but this change will be applied to Argobots 1.1. The user needs to be responsible for pool access management.
- `ABT_pool_def`: `u_get_type()`, `u_create_from_task()`, and `ABT_unit_get_task_fn` are unused. Instead, `u_create_from_thread()` is used for …
> pool: improve API

- Doxyfile.in
- src/arch/abtd_affinity.c
- src/arch/abtd_stream.c
- src/include/abt.h.in
- src/include/abtd.h
- src/stream.c
- test/basic/self_type.c
This PR improves the API and its explanation of `ABT_xstream_xxx()` functions for the upcoming Argobots 1.1.
This PR does not change the API of Argobots 1.0 except for the following.
- `ABT_xstream_free()`: returns `ABT_ERR_INV_XSTREAM` instead of `ABT_SUCCESS` when the user tries to free `ABT_XSTREAM_NULL`.
Freeing `ABT_XSTREAM_NULL` is an obvious error. `ABT_SUCCESS` should not be returned.
- `ABT_xstream_set_main_sched()`: allows changing a scheduler even if it has an empty pool.
There is no reason to return an error when a scheduler has an empty pool. It is the user's responsibility to schedule work units in a pool associated with the old scheduler.
This PR also fixes some bugs (e.g., `ABT_xstream_set_rank()`).
> xstream: improve API 

- Doxyfile.in
- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_pool.h
- src/pool/pool.c
- src/sched/sched.c
- src/stream.c
- src/thread.c
- src/thread_attr.c
- test/basic/self_type.c
- test/basic/thread_task.c
This PR improves the API and its explanation of `ABT_thread_xxx()` and `ABT_thread_attr_xxx()` functions for the upcoming Argobots 1.1.
This PR does not change the API of Argobots 1.0 except for the following.
- `ABT_thread_migrate_xxx()`: removes error checks for target threads/schedulers/pools/execution streams.
Since many instances are involved in the Argobots migration mechanism, it is practically impossible to atomically perform migration operations. Hence, the migration (implicitly) needed the user to guarantee that all targets are alive (i.e., not freed/terminated) during the migration process. Previous implementations of `ABT_thread_migrate_xxx()` checked some of them, but these checks are removed since the specification explicitly mentions that it is the user's responsibility.
If …
> thread: improve API

- Doxyfile.in
- src/barrier.c
- src/eventual.c
- src/futures.c
- src/mutex.c
- src/rwlock.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/sync_no_contention.c
This PR addresses the issue #287 from both documentation and implementation perspectives.
A ULT may yield when it tries to take a lock but that lock is already locked by another work unit, but otherwise a ULT should not yield -- this behavior is natural and intuitive. Since some users rely on this behavior, we should clarify this behavior in the function description. This PR also adds a test to examine this behavior.
At this point, this patch itself does not change the existing Argobots implementation since it satisfies this behavior.
> sync: ULTs should not yield if there is no contention

- test/basic/thread_attr.c
It seems that 8 KB ULT stack used in `test/basic/thread_attr.c` is too little on some platforms.  As far as I checked, 32-bit CentOS + clang 3.4.2 + some debugging options can sometimes cause SEGV because of stack overflow when `ABT_thread_get_attr()` is called in a ULT if (seemingly) the underlying execution stream has not executed `posix_memalign()` before and thus `posix_memalign()` internally called by `ABT_thread_get_attr()` takes a slow and deep execution path. I checked the function stack and `$esp`.
In any case, this SEGV is annoying and should be fixed.  This patch increases the size to 262144.
Note that the stack canary (#293) could not detect this issue since SEGV occurred first.  We need a page protection mechanism for debugging (though it is complicated and potentially …
> test/basic/thread_attr: increase the stack size

- src/include/abt.h.in
- src/mutex.c
- src/mutex_attr.c
- test/basic/mutex.c
- test/basic/mutex_recursive.c
This PR adds two new functions, `ABT_mutex_get_attr()` and `ABT_mutex_attr_get_recursive()`, which are useful to get a recursive property of a mutex.
They are implemented for completeness of the API, but these functions are useful for debugging too.
> mutex: add new functions to get a recursive property of a mutex

- src/arch/abtd_affinity.c
- src/arch/abtd_env.c
- src/global.c
- src/include/Makefile.mk
- src/include/abtd.h
- src/include/abti.h
- src/include/abti_error.h
- src/include/abti_global.h
- src/include/abti_key.h
- src/include/abti_mem.h
- src/include/abti_sched.h
- src/include/abti_stream.h
- src/include/abti_tool.h
- src/info.c
- src/key.c
- src/log.c
- src/mem/malloc.c
- src/pool/pool.c
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
- src/thread_attr.c
- src/tool.c
Some Argobots functions can be called without Argobots initialization; at least the description says so.  However, it is hard to guarantee such since its child function may access `gp_ABTI_global`, which is available only when Argobots is initialized.  Better support for functions under uninitialized Argobots is not only important to ensure the existing API but also useful to extend Argobots functionality (such as a static initializer of synchronization objects: #145).
This PR changes the current code so that internal functions that access `gp_ABTI_global` must take its as an argument. This change makes `gp_ABTI_global` dependency visible to top-level functions (e.g., public `ABT_xxx()` functions). This idea is similar to `p_local` and `p_local_xstream`.
This change should not have a …
> improve support for functions under uninitialized Argobots

- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_mutex.h
- src/mutex.c
- src/mutex_attr.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/mutex_static.c
Argobots assumes that the Argobots functionality is available only between `ABT_init()` and `ABT_finalize()`, so `ABT_mutex` can be created and used only when Argobots is initialized, but this makes it difficult to port existing Pthreads-based applications and runtimes if they do not have explicit initialization and finalization phases.  For example, some locks used in BOLT (Argobots-aware LLVM OpenMP) and Argobots-aware Open MPI can be called before `ABT_init()`, so currently those locks are implemented by combining `ABT_initialized()`, `ABT_thread_yield()`, and some atomic operations.  This is very cumbersome.
This PR provides a method to use an Argobots mutex even if Argobots is not initialized.  `ABT_mutex_memory` can be statically initialized.  Lock and unlock functions such as …
> mutex: mutex without Argobots initialization 

- Doxyfile.in
- src/cond.c
- src/include/abt.h.in
- test/.gitignore
- test/basic/Makefile.am
- test/basic/cond_static.c
This patch does the same thing as #299 for a condition variable. This addresses #145.
This should be useful to translate programs that use `pthread_mutex_t` and `pthread_cond_t`. This PR does not change the logic of `ABTI_cond`, so it won't affect the performance of existing Argobots programs.
> cond: using cond without Argobots initialization

- Doxyfile.in
- src/include/abt.h.in
- src/key.c
- src/self.c
- src/stream.c
- src/task.c
- src/thread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/self_rank_id.c
- test/basic/self_type.c
- test/basic/task_data.c
- test/basic/thread_data.c
- test/basic/thread_exit.c
- test/basic/thread_yield2.c
Argobots functions that get, set, or manipulate underlying threads and execution streams should be named "ABT_self_xxx()", but some functions do not follow this rule.  To improve the name consistency, this PR creates functions that have the same functionality as the existing ones but are named properly:
```
- ABT_xstream_self      -> ABT_self_get_xstream
- ABT_xstream_self_rank -> ABT_self_get_xstream_rank
- ABT_thread_self       -> ABT_self_get_thread
- ABT_thread_self_id    -> ABT_self_get_thread_id
- ABT_task_self         -> ABT_self_get_task
- ABT_task_self_id      -> ABT_self_get_task_id
- ABT_key_set           -> ABT_self_set_specific
- ABT_key_get           -> ABT_self_get_specific
- ABT_thread_yield      -> ABT_self_yield
- ABT_thread_exit       -> ABT_self_exit
```
Note that this …
> self: give new names to functions that target underlying ULTs or ESs

- configure.ac
- src/arch/abtd_env.c
This PR fixes #93 by detecting the huge page size at configure time.
This fix does not affect the most users who use x86/64 (huge page size was statically set to 2MB and will be set to 2MB by this auto detection system). On non-x86/64 machines, Argobots might start to use huge pages, which was disabled by default.
This PR also adds a size check to make `ABT_MEM_PAGE_SIZE` a power of two.
> mem: fix memory allocation

- Doxyfile.in
- examples/scheduling/sched_and_pool_user.c
- examples/stencil/stencil_forkjoin_divconq_hrws.c
- src/global.c
- src/include/Makefile.mk
- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_unit.h
- src/info.c
- src/log.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/stream.c
- src/task.c
- src/thread.c
- src/unit.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/pool_custom.c
- test/leakcheck/.gitignore
- test/leakcheck/Makefile.am
- test/leakcheck/pool.c
- test/leakcheck/unit.c
This patch fixes #316.
Whenever Argobots changes the unit-pool association (e.g., by using `ABT_unit_set_associated_pool()`, `ABT_xstream_set_main_sched()`, `ABT_pool_push()`, or `ABT_xstream_run_unit()`), the unit associated with the old pool must be freed (`u_free()`) and its thread's "unit" must be renewed by a new pool (`u_create_from_thread()`).
Argobots does not do this, which leaks resources and/or calls pool/unit functions that are not associated with a given `ABT_unit`.  This is also an API-level issue: `ABT_unit_set_associated_pool(ABT_unit unit, ABT_pool pool)` changes the associated pool of \c unit to \c pool, but then \c unit should be changed according to the new pool's `ABT_unit` representation.  Since this function does not take an old pool, the Argobots runtime cannot …
> fix unit-pool mapping

- src/include/abti.h
- src/sched/sched.c
- src/stream.c
- src/thread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/xstream_set_main_sched.c
This PR fixes the bug that #318 missed. This bug happens when `ABT_xstream_set_main_sched()` is called to update the underlying execution stream's main scheduler and the new scheduler's pool is shared with other schedulers associated with already running execution streams.
In `ABT_xstream_set_main_sched()`, the caller ULT frees the main scheduler (say S1) when it updates its underlying main scheduler.  If the caller ULT is scheduled by another scheduler, however, S1 that is still used by the execution stream that originally calls `ABT_xstream_set_main_sched()` can be freed.
This PR fixes it by using a request mechanism to release a scheduler. This PR also adds a test `xstream_set_main_sched` to check such a case by stressing `ABT_xstream_set_main_sched()` and …
> xstream: fix xstream_set_main_sched (cont.)

- src/arch/fcontext/jump_arm64_aapcs_macho_gas.S
This PR fixes floating-point register management error on the new ARM-based Apple Chip.
Apple M1 Chip employs a 64-bit ARM-based architecture.  The default C compiler, as far as I checked, defines `__VFP_FP__` and/or `__SOFTFP__` differently.  Since people do not use ARM-based macOS other than the M1 chip, we should remove those macros to make Argobots work on M1.
Now Argobots passes all the tests on M1 as far as I checked.
We officially support the new Apple M1 Chip (as well as OSX), so please feel free to report any issues!
We note that, currently, the Argobots team cannot regularly access to M1. Once we deploy an M1 machine, we will test Argobots on M1 regularly.
> fcontext/arm64/osx: fix jump_fcontext for Apple M1 Chip

- src/include/abt.h.in
`ABT_XXX_MEMORY_INITIALIZER` does not exist.  The correct name is `ABT_XXX_INITIALIZER` (e.g., `ABT_MUTEX_MEMORY_INITIALIZER`).  This patch fixes the comments.
Note that this patch does not affect any existing functionalities.
> abt.h: fix comments on ABT_mutex_memory and ABT_cond_memory

- src/arch/abtd_env.c
- test/basic/stack_guard.c
PR #327 did not consider a system that has larger page sizes. For example, typically Intel x86/64 machines use 4KB pages while the other systems such as 64-bit ARM and POWER9 sometimes use 64KB pages or larger. This PR fixes the test as well as the stack size adjustment to support those systems.
This PR does not affect the behavior of Argobots unless you enable this stack guard.
> thread: fix mprotect-based stack guard 

- configure.ac
- src/arch/abtd_env.c
- src/include/abti.h
- src/info.c
- src/ythread.c
This PR fixes #329.
Even if the stack unwinding feature is enabled (i.e., Argobots is compiled with libunwind) , Argobots dumps the raw ULT stack as well as the human-readable function trace. However, most developers cannot understand the raw stack.
```
...
000055f0d40accd0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
000055f0d40accf0: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
000055f0d40acd10: 0000000000000000 00000000000202f1 000055f0d40acbd0 00007f6b11440be0
000055f0d40acd30: 0000000000000020 0000000000000050 000055f0d40acd80 0000000000008000
...
```
This PR adds two ways to disable it.
Pass `--enable-stack-unwind=unwind-only` at configure time.  This disables the raw stack dump by default.
```sh
./configure …
```
> info: suppress raw stack dump when it is requested

- src/util/largepage.c
`fd` must be `-1` when `MAP_ANONYMOUS` or `MAP_ANON` is set for portability. For example, `mmap()` fails on FreeBSD if `fd` is `0`.  Note that Linux accepts both `0` and `-1`.
Linux `mmap()`:
https://man7.org/linux/man-pages/man2/mmap.2.html
FreeBSD `mmap()`:
https://www.freebsd.org/cgi/man.cgi?query=mmap&sektion=2&format=html
> util: fix an argument of mmap

- configure.ac
Debug-logging and error-code printing should be orthogonal, but the current Argobots enables error-code printing (`--enable-debug=err`) if debug-logging is enabled (`--enable-debug=log`). The idea behind this change is that relying on error handling of Argobots is totally legal; error handling in Argobots gets more mature.
This patch cleans up the `--enable-debug` option.
1. Remove `debug_err=yes`, which enables printing the error code, from `--enable-debug=log`.  To enable this, `--enable-debug=err` must be set.
2. Clarify that `--enable-debug=all` and `most` include `--enable-debug=err`.
This PR changes the behavior of `--enable-debug=log`; it does not print the error code in the latest version.  The previous
`--enable-debug=log` is equivalent to the current `--enable-debug=log,err`.
> configure: clean up --enable-debug option

- src/cond.c
- src/include/abti_waitlist.h
`ABTI_waitlist_is_empty()` returned `ABT_TRUE` if the `ABTI_waitlist` is "not" empty, but it worked correctly since its caller (`ABT_cond_free()`) also misused this function as if this function is "`ABTI_waitlist_not_empty()`". 
This patch fixes the implementation of `ABTI_waitlist_is_empty()` so that its name correctly explains what its body.
Note that this fix does not affect the behavior of Argobots.
> waitlist: fix ABTI_waitlist_is_empty

- configure.ac
- src/barrier.c
- src/cond.c
- src/eventual.c
- src/futures.c
- src/global.c
- src/include/abti.h
- src/include/abti_cond.h
- src/include/abti_error.h
- src/include/abti_mutex.h
- src/info.c
- src/key.c
- src/mutex.c
- src/mutex_attr.c
- src/pool/pool.c
- src/rwlock.c
- src/sched/sched.c
- src/self.c
- src/stream.c
- src/stream_barrier.c
- src/task.c
- src/thread.c
- src/thread_attr.c
- src/timer.c
- src/tool.c
- src/unit.c
This PR closes #315.
Argobots defines when undefined behaviors may happen but the runtime does not actively detect such since such a check is either mostly unnecessary (e.g., check if Argobots is initialized or not) or extremely costly (e.g., detection of double-freeing an Argobots object). This PR provides an option to check some of them on a best efforts basis.
Even after this PR, Argobots checks only runtime initialization and NULL arguments in most places. Some checks regarding synchronization objects, however, would be generally useful (e.g., check if there's no waiter when freeing `ABT_eventual`). We might add more expensive checks if needed.
Note that this does not break the current API since "undefined behavior" can cause anything, including failure of `assert()`. At the same …
> error: assert when undefined behavior may occur

- src/include/abtd_ucontext.h
This patch fixes a bug that can break the vectorized floating-point computation results on POWER9 (possibly only when Clang 10.0 is used). This PR introduces a workaround that works so far, but I did not identify the real cause.
I spent a day, but I could not identify the problem.  It seems that the VRSAVE register (precisely speaking, memory that saves the VRSAVE register's value in `ucontext_t`) gets broken if we lazily initialize `ucontext_t` via `getcontext()`, possibly because the VRSAVE value of a newly created POSIX-thread (via `pthread_create()`) is not proper to run vectorized floating-point operations.  To be honest, I don't know how this register affects the results and who should manage this value (the ABI specification says "Reserved for system use. This register should not …
> fix a ucontext + POWER9 + vectorization bug

- configure.ac
- src/arch/abtd_env.c
- src/include/abtd.h
- src/info.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/info_query.c
ULT stack overflow causes numerous issues (see #274, #324, #333, and [this thread](https://lists.argobots.org/pipermail/discuss/2021-April/000113.html)). This PR adds new features to ease stack size configuration.
The user can configure a default ULT stack size.
```sh
./configure --enable-default-stacksize=102400
```
This setting can be overwritten by `ABT_THREAD_STACKSIZE`
```sh
./a.out
ABT_THREAD_STACKSIZE=204800 ./a.out
```
**If `--enable-ver20-api` is set,** the application can now obtain the default stack size via `ABT_info_query_config()` without initializing Argobots (i.e., before `ABT_init()`).
```c
// Argobots configured with --enable-ver20-api
size_t stacksize;
ABT_info_query_config(ABT_INFO_QUERY_KIND_DEFAULT_THREAD_STACKSIZE, (void *)&stacksize);
assert(stacksize >= 65536); …
```
> improve ULT stack size configuration

- src/arch/abtd_ythread.c
- src/arch/fcontext/fcontext_arm64_aapcs_elf_gas.S
- src/arch/fcontext/fcontext_arm64_aapcs_macho_gas.S
- src/arch/fcontext/fcontext_i386_sysv_elf_gas.S
- src/arch/fcontext/fcontext_ppc64_sysv_elf_gas.S
- src/arch/fcontext/fcontext_x86_64_sysv_elf_gas.S
- src/arch/fcontext/fcontext_x86_64_sysv_macho_gas.S
- src/global.c
- src/include/abtd_fcontext.h
- src/include/abtd_ucontext.h
- src/include/abti.h
- src/include/abti_event.h
- src/include/abti_waitlist.h
- src/include/abti_ythread.h
- src/self.c
- src/stream.c
- src/thread.c
- src/ythread.c
Some threading functions need to perform an operation to complete *after context switching*.  For example, a ULT that yields needs to be pushed back to its associated pool after it switches to its parent ULT (otherwise, another scheduler accesses that pool and executes that ULT which is still running, crashing the program).  Such an operation across context switch is achieved by request handling: before a ULT yields, this ULT sets a "POOL_PUSH" request, and the resuming ULT (= the parent scheduler) executes a pool operation based on its request.
This request handling mechanism is very complicated since the developer does not know which request handling would be performed by which ULT.  For example, a join-termination request attached to a joinee (i.e., a ULT that finishes) is handled only …
> improve ULT request handling mechanism

- src/self.c
This PR fixes #341. Specifically, this PR suppresses a warning message when `ABT_self_get_type()` (Argobots 1.x) is called on an external thread.  This warning message was printed when `--enable-debug=err` (included by `most` or `all`) is set.
(Note that `ABT_initialized()`, `ABT_mutex_trylock()`, and `ABT_cond_timedwait()` also legally return an error like `ABT_self_get_type()`. They do not print a warning message.)
> self: suppress warning message of ABT_self_get_type

- src/arch/abtd_ythread.c
- src/include/abt.h.in
- src/include/abtd.h
- src/include/abti.h
- src/include/abti_ythread.h
- src/self.c
- src/thread.c
- src/ythread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/self_exit_to.c
- test/basic/self_suspend_to.c
- test/basic/self_yield_to.c
This PR implements the following new APIs, which become feasible thanks to #342.
```c
int ABT_self_yield_to(ABT_thread thread);
int ABT_self_suspend_to(ABT_thread thread);
int ABT_self_exit_to(ABT_thread thread);
```
Specifically, `ABT_self_yield_to()` is an important API since it can replace the current `ABT_thread_yield_to()`; `ABT_thread_yield_to()` internally uses `pool_remove()`, which is **not thread-safe**, so the target ULT of `ABT_thread_yield_to()` must be in a pool that is accessed by no other ULTs/execution streams in parallel.  This restriction makes `ABT_thread_yield_to()` useless.
To do something similar to `ABT_thread_yield_to()`, the user can do the following:
```c
// mimic ABT_thread_yield_to()
void thread_yield_to(ABT_thread thread) {
ABT_pool pool;
ABT_unit unit; …
```
> self: add ABT_self_yield_to and its friends

- examples/fibonacci/fibonacci.c
- examples/stencil/.gitignore
- examples/stencil/Makefile.am
- examples/stencil/stencil_forkjoin_divconq_rws_cf.c
- src/include/abt.h.in
- src/thread.c
- test/.gitignore
- test/basic/Makefile.am
- test/basic/thread_create3.c
- test/basic/thread_create4.c
- test/leakcheck/thread.c
This PR closes #155.
Everyone loves child-first scheduling.  This PR implements `ABT_thread_create_to()` which enables child-first thread creation.  `ABT_thread_create_to()` creates a ULT and jumps to that ULT after pushing the calling ULT to its associated pool.
Note that currently, the pool (=task queue) management is different from that of Cilk, so the behavior is not the same as the typical Cilk-like child-first random-work stealing.  This needs #154, which hasn't been implemented yet.
Typically, divide-and-conquer recursive parallel algorithms prefer child-first scheduling.  The following shows the performance of divide-and-conquer 2D stencil computation.
Note that this benchmark does not optimize the stencil kernel (e.g., by vectorization), so the performance should be suboptimal. …
> implement a child-first scheduling option

- src/ythread.c
This PR removes comments wrongly left by #342. Those comments do not use `/**/`.  This patch removes them since they are unnecessary.
> ythread: remove unnecessary comments

- src/include/abt.h.in
- src/thread.c
- test/basic/thread_create4.c
- test/basic/thread_revive.c
Related to #345. This PR implements a child-first ULT revival operation.
```c
int ABT_thread_revive_to(ABT_pool pool, void (*thread_func)(void *), void *arg, ABT_thread *thread);
```
> thread: add ABT_thread_revive_to

- src/include/abt.h.in
- src/include/abti.h
- src/include/abti_ythread.h
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/self.c
- src/stream.c
- src/thread.c
- test/basic/sched_on_thread.c
- test/basic/xstream_set_main_sched.c
This PR implements a new API `ABT_self_schedule()`, which is similar to `ABT_xstream_run_unit()`.
```c
int ABT_self_schedule(ABT_thread thread, ABT_pool pool);
```
The difference is the following two points.
1. `ABT_self_schedule()` takes `ABT_thread`, not `ABT_unit`.
2. `ABT_self_schedule()` accepts `ABT_POOL_NULL`, and if so, pool association of `thread` is not changed.
This PR completes all the basic context switching functions that bypass a scheduler. The new set of API should give users full flexibility of ULT scheduling; it should be especially useful to implement special ULT synchronization mechanisms on top of Argobots.
This patch does not affect the existing API.
> self: add ABT_self_schedule

- configure.ac
- src/include/abti.h
- src/include/abti_stream.h
- src/include/abti_thread.h
- src/include/abti_ythread.h
- src/info.c
- src/stream.c
- src/thread.c
- src/ythread.c
Currently, Argobots supports two types of asynchronous requests for threads: cancellation and migration.  Now both are checked on context switching, but those requests can break the algorithm (e.g., cancelling a ULT that is waiting for a synchronization object). This can be the user's responsibility, but the runtime should ignore those requests if it can potentially break the algorithm since migration and cancellation timings are not defined.
This patch fixes this request handling algorithm and cleans it up to make its logic simpler.
As a result, this PR reduces the number of request handling sites, so this PR should not degrade the performance of the Argobots runtime.  This PR should not affect most user programs because most users do not use these features.
If you find any issues, …
> thread: fix asynchronous request handling

- Doxyfile.in
- src/include/abt.h.in
- src/sched/config.c
- test/basic/sched_config.c
This PR adds two new functions to provide simpler interface to access `ABT_sched_config`.
```c
int ABT_sched_config_set(ABT_sched_config config, int idx, ABT_sched_config_type type, const void *val);
int ABT_sched_config_get(ABT_sched_config config, int idx, ABT_sched_config_type *p_type, void *val);
```
Those functions are simpler than existing variadic functions:
```c
int ABT_sched_config_create(ABT_sched_config *config, ...);
int ABT_sched_config_read(ABT_sched_config config, int num_vars, ...);
```
To be honest, I do not remember arguments for `...`.
This PR also fixes several issues including memory leak.
> improve ABT_sched_config

- examples/profiling/async_engine.c
- examples/scheduling/sched_and_pool_user.c
- examples/scheduling/sched_user.c
- examples/stencil/stencil_forkjoin_divconq_hrws.c
- src/include/abt.h.in
- src/include/abti_log.h
- src/include/abti_pool.h
- src/log.c
- src/pool/pool.c
- test/basic/pool_user_def.c
- test/basic/sched_on_thread.c
- test/basic/xstream_set_main_sched.c
This PR adds new pool functions to use a custom pool defined by `ABT_pool_user_def`. New features include `p_push_many`, `p_pop_many`, and `ABT_pool_context`.
```c
int ABT_pool_pop_thread(ABT_pool pool, ABT_thread *thread);
int ABT_pool_pop_thread_ex(ABT_pool pool, ABT_thread *thread, ABT_pool_context pool_ctx);
int ABT_pool_pop_threads(ABT_pool pool, ABT_thread *threads, size_t len, size_t *num);
int ABT_pool_pop_threads_ex(ABT_pool pool, ABT_thread *threads, size_t len, size_t *num,
ABT_pool_context pool_ctx);
int ABT_pool_push_thread(ABT_pool pool, ABT_thread thread);
int ABT_pool_push_thread_ex(ABT_pool pool, ABT_thread thread, ABT_pool_context pool_ctx);
int ABT_pool_push_threads(ABT_pool pool, const ABT_thread *threads, size_t num);
int ABT_pool_push_threads_ex(ABT_pool pool, const …
```
> new pool API for ABT_pool_user_def

- examples/scheduling/sched_and_pool_user.c
- src/include/abt.h.in
- src/include/abti_log.h
- src/include/abti_pool.h
- src/info.c
- src/log.c
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
- src/thread.c
- test/basic/pool_custom.c
- test/basic/pool_user_def.c
- test/leakcheck/pool.c
- test/leakcheck/unit.c
**This does not affect the API defined in the Argobots 1.1 specification.**
This PR fixes the API defined by #354.
Currently, Argobots internally employs a ABT_unit to ABT_thread hash table for some legacy APIs that take `ABT_unit` but not taking its associated pool (`ABT_pool`) (see #317).  Note that getting `ABT_unit` from `ABT_thread` is easy since `ABT_thread` saves this information.
We would like to remove this hash table since it is heavy (at most `malloc()` + spinlock).
The following legacy functions have this issue:
```c
int ABT_xstream_run_unit(ABT_unit unit, ABT_pool pool);
// Replacement:
// int ABT_self_schedule(ABT_thread thread, ABT_pool pool);
int ABT_pool_push(ABT_pool pool, ABT_unit unit);
// Replacement:
// int ABT_pool_push_thread(ABT_pool pool, ABT_thread thread);
int …
```
> pool: change argument/return types of a few ABT_pool_user_def functions

- examples/fibonacci/fibonacci.c
- src/include/abt.h.in
- src/include/abti.h
- src/pool/Makefile.mk
- src/pool/fifo.c
- src/pool/fifo_wait.c
- src/pool/pool.c
- src/pool/randws.c
- src/pool/thread_queue.h
- test/basic/pool_custom.c
- test/leakcheck/pool.c
This patch implements a built-in random work-stealing pool (`ABT_POOL_RANDWS`), which is known to be efficient for task-parallel applications.  The user is recommended to use this pool with `ABT_SCHED_RANDWS`.
Specifically, this pool pushes a work unit to the head if the work unit is created or revived while it pushes a yielded/resumed ULT to the tail. Its remote pop (in the context of random work stealing) is from the tail while its local pop is from the head.
The performance improvement can be significant.  The following shows the Fibonacci performance (see `examples/fibonacci`) on Intel Skylake, 64-bit ARM, and POWER9 machines.  It indicates that RANDWS shows significantly better performance (more than 10x) and scalability.
<details><summary> Experimental setting (collapsed)</summary> …
> pool: implement a random work-stealing pool

- configure.ac
This PR sets `--disable-simple-mutex` at configure time by default.
Because of several bugs in "the non-simple mutex" (#14, #34, #41), the simple mutex became the default implementation for correctness (#102). The simple mutex is yield-based, so most users do not expect this behavior (see #361). The "non-simple mutex" has been reasonably fixed by #268, which can be enabled by setting "--disable-simple-mutex". As requested by several users, this PR now changes the default mutex implementation.
The previous default mutex (= `--enable-simple-mutex`) should be slightly faster if the mutex is not contended. The new default mutex (= `--disable-simple-mutex`) should be more efficient if contention happens.  Since some synchronization objects such as `ABT_rwlock` internally uses the logic of …
> configure: disable simple mutex by default

- src/eventual.c
- src/include/abt.h.in
- test/.gitignore
- test/basic/Makefile.am
- test/basic/eventual_static.c
- test/basic/ext_thread_eventual.c
This PR fixes #362. Specifically, this PR implements a static initializer for `ABT_eventual`. The static initializer is cheaper than `ABT_eventual_create()`. There's no need to explicitly free a statically initialized eventual, so it might be easy to handle in some cases.
Note that a statically initialized `ABT_eventual` does not accept `nbytes`. Setting a value is prohibited.
@mdorier: For possible future optimizations, `ABT_eventual` functions require Argobots initialization unlike `ABT_mutex` and `ABT_cond`; some (not all) `ABT_mutex/cond` functions can be called before `ABT_init()` and after `ABT_finialize()` (see #299). If you need this for `ABT_eventual`, please leave a comment.
> eventual: provide a static initializer for eventual

- src/pool/pool.c
`ABTI_pool_pop_timedwait()` does not properly handle `ABT_UNIT_NULL`, so it causes SEGV if a user-defined `p_pop_timedwait()` returns `ABT_UNIT_NULL`. This issue was introduced by #357. This patch adds a branch to deal with `ABT_UNIT_NULL`.
This PR should fix #365. Thank you for reporting this issue, @mdorier!
> pool: fix ABTI_pool_pop_timedwait

- configure.ac
This PR modifies the CFLAGS used in configure.ac temporarily for the 128-bit CAS test.  This is necessary because the test relies on a header file within the source directory.  Without this PR the 128-bit CAS test may erroneously fail for out-of-tree builds.
Fixes #370
> adjust include path for 128-bit CAS autoconf test

- src/sched/basic.c
- src/sched/basic_wait.c
- src/sched/prio.c
- src/sched/randws.c
Fixes the case where `num_pools` is 0 in the schedulers implementation. See issue https://github.com/pmodels/argobots/issues/381.
> added case num_pools == 0 in schedulers

- src/info.c
Revival of the PR #394 from @bfaccini.
1/one returned value must be tested instead of 0 to detect that last "parked" XStream is done in ABTI_info_check_print_all_thread_stacks() and thus that print_stack_flag can be reset to PRINT_STACK_FLAG_UNSET to allow for a next dump to be started.
[DAOS-14248](https://daosio.atlassian.net/browse/DAOS-14248) ticket, Argobots issue pmodels#393.
> info: fix ULTs stacks dump works only once

- configure.ac
The commit 3196bbf3d05702b7f124ac7cd6a13ad9cf585caf removed the support of libunwind.
From the message https://github.com/pmodels/argobots/commit/3196bbf3d05702b7f124ac7cd6a13ad9cf585caf#r143955103, it seems to not be intentional.
DAOS-15596 ticket, Update Argobots to 1.2
> configure: Restore libuwnind support
